# -*- coding: utf-8 -*-
# 부서별 실제 소관업무 데이터 (jeju_dept_report.md + division SP + gov-router.js 근거)
# duties: 실제 문서에 등장한 구체적 업무/제도명 (가능한 한 실제 근거 문구 사용)
# level: 확인상태 등급(①~⑤) 그대로 유지
# superior: 이 부서에 "내부지시"를 내릴 법한 상급기관(도지사/행정부지사/기획조정실/해당 중앙부처 등)

DEPARTMENTS = [
 # 1. 기획조정실
 dict(sil="기획조정실", name="정책기획관", sp="SP-DIV-PLAN-POLICY", level="①",
      duties=["도정 종합계획 수립", "성과관리 지표·평가(지방자치단체 합동평가)", "실국 협의를 통한 특정 사업 확정"],
      superior="행정부지사"),
 dict(sil="기획조정실", name="예산담당관", sp="SP-DIV-PLAN-BUDGET", level="①",
      duties=["예산편성(지방재정법 기준)", "제주도 예산 주요 사업 반영 여부", "도의회 예산안 의결 대응"],
      superior="기획조정실장"),
 dict(sil="기획조정실", name="청년정책담당관", sp="SP-DIV-PLAN-YOUTH", level="①",
      duties=["청년월세지원사업", "청년 희망충전 월세 지원사업(35~39세)", "청년 소득요건 심사 안내"],
      superior="기획조정실장"),
 dict(sil="기획조정실", name="특별자치법무담당관", sp="SP-DIV-PLAN-LEGAL", level="①",
      duties=["제주특별법 특례 제도 안내", "조례 제·개정 절차", "법률자문 연계(변호사·법제처)"],
      superior="행정부지사"),
 dict(sil="기획조정실", name="세정담당관", sp="SP-DIV-PLAN-TAXADMIN", level="①",
      duties=["지방세 세목 체계(지방세법 기준)", "세정 정책 방향", "지방세 감면 특례 확인"],
      superior="기획조정실장"),
 dict(sil="기획조정실", name="인구정책담당관", sp="SP-DIV-PLAN-POPULATION", level="①",
      duties=["탐라청년출발패키지(청년 전입 축하장려금)", "외국인주민·다문화가족 지원정책"],
      superior="행정부지사"),
 dict(sil="기획조정실", name="혁신관리기획관", sp="SP-DO-PLAN(신설,미작성)", level="②",
      duties=["업무혁신·성과관리·공약관리 통합", "공공기관 총괄관리"],
      superior="도지사"),

 # 2. 특별자치행정국
 dict(sil="특별자치행정국", name="자치행정과", sp="SP-DIV-JACHI-SELFGOV", level="①",
      duties=["정착주민 지역공동체 조성 지원(제주愛in)", "특별자치제도·조직개편 안내"],
      superior="특별자치행정국장"),
 dict(sil="특별자치행정국", name="총무과", sp="SP-DIV-JACHI-GENERAL", level="①",
      duties=["정보공개청구 절차", "도청 조직·연락처 안내", "내부 인사발령·채용"],
      superior="특별자치행정국장"),
 dict(sil="특별자치행정국", name="회계과", sp="SP-DIV-JACHI-ACCOUNTING", level="①",
      duties=["도유재산 관리(공유재산 및 물품 관리법)", "재산 대부·사용허가 절차"],
      superior="특별자치행정국장"),
 dict(sil="특별자치행정국", name="4·3지원과", sp="SP-DIV-JACHI-43SUPPORT", level="①",
      duties=["4·3희생자 보상금 지급기준", "보상금 신청 접수(등기우편 포함)"],
      superior="4·3위원회(행정안전부)"),
 dict(sil="특별자치행정국", name="특별자치제도추진단", sp="SP-DO-AUTONOMY", level="①",
      duties=["특별자치제도·분권 제도", "특례 확대 관련 안내"],
      superior="특별자치행정국장"),
 dict(sil="특별자치행정국", name="자치분권협력과", sp="(미작성)", level="④",
      duties=["자치분권 정책 협력(통상 정의, 재검증 필요)"],
      superior="특별자치행정국장"),

 # 3. 경제활력국
 dict(sil="경제활력국", name="경제정책과", sp="SP-DO-ECON", level="②",
      duties=["민생경제정책 총괄", "사회연대경제·로컬경제 지원", "탐나는전(지역화폐)·제로페이 통합"],
      superior="경제활력국장"),
 dict(sil="경제활력국", name="기업정책과", sp="SP-DO-ECON", level="②",
      duties=["창업 지원", "기업성장·투자유치·기업지원 전주기 지원"],
      superior="경제활력국장"),
 dict(sil="경제활력국", name="소상공인물류과", sp="SP-DO-ECON", level="②",
      duties=["소상공인 지원(자율상권구역 지정 등)", "물류 정책 연계"],
      superior="경제활력국장"),
 dict(sil="경제활력국", name="고용센터(사업소 전환)", sp="SP-DO-ECON", level="②",
      duties=["구직자·기업 대상 고용서비스", "일자리 미스매치 해소"],
      superior="경제활력국장"),

 # 4. 미래산업국
 dict(sil="미래산업국", name="디지털혁신과", sp="SP-DIV-INNOV-DIGITAL", level="①",
      duties=["디지털 전환·스마트시티 정책", "개별 지원사업 심사 안내"],
      superior="미래산업국장"),
 dict(sil="미래산업국", name="미래성장과", sp="SP-DIV-INNOV-FUTUREGROWTH", level="①",
      duties=["신산업 육성 정책", "신산업 지원사업 확정 절차"],
      superior="미래산업국장"),
 dict(sil="미래산업국", name="우주모빌리티과", sp="SP-DIV-INNOV-SPACEMOBILITY", level="①",
      duties=["UAM(도심항공교통) 추진현황", "드론 관련 정책"],
      superior="미래산업국장"),

 # 5. 기후환경국/기후에너지국
 dict(sil="기후환경국", name="기후대응과", sp="(미작성)", level="④",
      duties=["탄소중립·기후적응 정책 총괄(통상 정의, 재검증 필요)"],
      superior="기후환경국장"),
 dict(sil="기후환경국", name="환경보전과", sp="(미작성)", level="④",
      duties=["대기·수질 등 환경보전 정책(통상 정의, 재검증 필요)"],
      superior="기후환경국장"),
 dict(sil="기후환경국", name="자원순환과", sp="(미작성)", level="④",
      duties=["폐기물 정책·자원순환 총괄(통상 정의, 재검증 필요)"],
      superior="기후환경국장"),
 dict(sil="기후에너지국(신설)", name="탄소중립정책과", sp="(미작성)", level="②",
      duties=["탄소중립정책(기후환경국에서 이관)"],
      superior="기후에너지국장"),
 dict(sil="기후에너지국(신설)", name="분산에너지과", sp="(미작성)", level="②",
      duties=["분산에너지 정책", "재생에너지 보급·확산"],
      superior="기후에너지국장"),

 # 6. 도시건설국
 dict(sil="도시건설국", name="주택정책과", sp="(미작성)", level="③",
      duties=["공공임대주택 등 주택정책(통상 정의, 재검증 필요)"],
      superior="도시건설국장"),
 dict(sil="도시건설국", name="건설행정과", sp="(미작성)", level="③",
      duties=["건설업 등록", "건설엔지니어링업 등록", "하도급계약심사(통상 정의, 재검증 필요)"],
      superior="도시건설국장"),
 dict(sil="도시건설국", name="도로과", sp="(미작성)", level="③",
      duties=["도(道) 관리 도로망 확충·유지보수 계획(통상 정의, 재검증 필요)"],
      superior="도시건설국장"),
 dict(sil="도시건설국", name="하천과", sp="(미작성)", level="③",
      duties=["하천 정비·재해예방(통상 정의, 재검증 필요)"],
      superior="도시건설국장"),

 # 7. 교통항공국
 dict(sil="교통항공국", name="대중교통과", sp="(미작성)", level="③",
      duties=["버스 준공영제", "교통약자 콜택시", "공영주차장 정책(통상 정의, 재검증 필요)"],
      superior="교통항공국장"),
 dict(sil="교통항공국", name="교통정책과", sp="(미작성)", level="③",
      duties=["교통 종합계획", "교통영향평가(통상 정의, 재검증 필요)"],
      superior="교통항공국장"),
 dict(sil="교통항공국", name="공항확충지원단", sp="SP-DO-AIRPORTSUP", level="①",
      duties=["제2공항 공항확충 사업 관련 안내"],
      superior="교통항공국장"),
 dict(sil="교통항공국", name="제2공항상생지원단(소통제2공항담당관)", sp="(미작성)", level="②",
      duties=["제2공항 관련 주민소통·주민지원", "지역사회 상생협력"],
      superior="교통항공국장"),

 # 8. 복지가족국
 dict(sil="복지가족국", name="복지정책과", sp="SP-DIV-WELFARE-POLICY", level="①",
      duties=["국민기초생활보장제도(생계·의료·주거·교육급여)", "복지 제도 최초 상담·연계"],
      superior="복지가족국장"),
 dict(sil="복지가족국", name="아동보육청소년과", sp="SP-DIV-WELFARE-CHILDCARE", level="①",
      duties=["아동수당(만 9세 미만)", "부모급여(0세 월100만/1세 월50만)", "첫만남이용권"],
      superior="복지가족국장"),
 dict(sil="복지가족국", name="장애인복지과", sp="SP-DIV-WELFARE-DISABLED", level="①",
      duties=["장애인연금·장애수당", "활동지원 제도", "장애인 등록 절차"],
      superior="복지가족국장"),
 dict(sil="복지가족국", name="노인복지과", sp="SP-DIV-WELFARE-ELDERLY", level="①",
      duties=["기초연금(선정기준·신청방법)", "노인일자리·경로당 프로그램"],
      superior="복지가족국장"),
 dict(sil="복지가족국", name="여성가족과", sp="(미작성)", level="④",
      duties=["한부모가족·다문화가족 지원(통상 정의, 재검증 필요)"],
      superior="복지가족국장"),

 # 9. 도민안전건강실
 dict(sil="도민안전건강실", name="안전정책과", sp="SP-DIV-SAFETY-POLICY", level="①",
      duties=["재난안전 정책·시설 안전점검", "안전신문고 신고 경로"],
      superior="도민안전건강실장"),
 dict(sil="도민안전건강실", name="자연재난과", sp="SP-DIV-SAFETY-NATURALDISASTER", level="①",
      duties=["재난지원금 지급기준", "태풍·호우 피해신고 절차"],
      superior="도민안전건강실장"),
 dict(sil="도민안전건강실", name="사회재난과", sp="SP-DIV-SAFETY-SOCIALDISASTER", level="①",
      duties=["감염병 위기경보 단계", "사회재난 유형·대응체계"],
      superior="도민안전건강실장"),
 dict(sil="도민안전건강실", name="보건정책과", sp="SP-DIV-SAFETY-HEALTHPOLICY", level="①",
      duties=["공공보건의료 정책·보건소 체계", "의료기관 개설 절차(의료법)"],
      superior="도민안전건강실장"),
 dict(sil="도민안전건강실", name="건강위생과", sp="SP-DIV-SAFETY-HEALTHHYGIENE", level="①",
      duties=["식품접객업 영업신고(식품위생법)", "식중독 의심신고 경로"],
      superior="도민안전건강실장"),

 # 10. 문화체육교육국
 dict(sil="문화체육교육국", name="문화정책과", sp="(미작성)", level="③",
      duties=["문화예술 진흥 종합계획(통상 정의, 재검증 필요)"],
      superior="문화체육교육국장"),
 dict(sil="문화체육교육국", name="체육진흥과", sp="(미작성)", level="③",
      duties=["생활체육·전문체육 진흥, 체육시설 정책(통상 정의, 재검증 필요)"],
      superior="문화체육교육국장"),
 dict(sil="문화체육교육국", name="평생교육과", sp="(미작성)", level="③",
      duties=["평생학습 진흥, 도서관 정책 총괄(통상 정의, 재검증 필요)"],
      superior="문화체육교육국장"),

 # 11. 관광교류국
 dict(sil="관광교류국", name="관광정책과", sp="(미작성)", level="③",
      duties=["관광 종합계획, 숙박업·여행업 정책(통상 정의, 재검증 필요)"],
      superior="관광교류국장"),
 dict(sil="관광교류국", name="관광마케팅과", sp="(미작성)", level="③",
      duties=["국내외 관광 마케팅·홍보(통상 정의, 재검증 필요)"],
      superior="관광교류국장"),
 dict(sil="관광교류국", name="국제교류과", sp="(미작성)", level="③",
      duties=["자매도시·국제교류 협력(통상 정의, 재검증 필요)"],
      superior="관광교류국장"),

 # 12. 농축산식품국
 dict(sil="농축산식품국", name="농업정책과", sp="(미작성)", level="③",
      duties=["농업경영체 등록, 공익직불금 정책(통상 정의, 재검증 필요)"],
      superior="농축산식품국장"),
 dict(sil="농축산식품국", name="축산과", sp="(미작성)", level="③",
      duties=["축산업 허가, 가축방역 정책(통상 정의, 재검증 필요)"],
      superior="농축산식품국장"),
 dict(sil="농축산식품국", name="식품원예산업과", sp="(미작성)", level="③",
      duties=["감귤 등 원예작물 유통·가공산업 지원(통상 정의, 재검증 필요)"],
      superior="농축산식품국장"),

 # 13. 해양수산국
 dict(sil="해양수산국", name="수산정책과", sp="(미작성)", level="③",
      duties=["어업면허, 수산업 정책 총괄(통상 정의, 재검증 필요)"],
      superior="해양수산국장"),
 dict(sil="해양수산국", name="해양산업과", sp="(미작성)", level="③",
      duties=["양식업, 해양산업 육성(통상 정의, 재검증 필요)"],
      superior="해양수산국장"),
 dict(sil="해양수산국", name="어촌개발과", sp="(미작성)", level="③",
      duties=["마을어장·어촌 정주여건 개선사업(통상 정의, 재검증 필요)"],
      superior="해양수산국장"),

 # 14. 소통·청렴·브랜드 계열
 dict(sil="소통담당관", name="소통담당관", sp="SP-DO-COMM", level="②",
      duties=["도민소통 채널 운영", "정책 갈등관리·공론화"],
      superior="도지사"),
 dict(sil="소통담당관", name="제주브랜드담당관", sp="(미작성)", level="②",
      duties=["제주 브랜드 전략", "브랜드 마케팅"],
      superior="도지사"),
 dict(sil="청렴감찰관", name="청렴감찰관", sp="SP-DO-INTEGRITY", level="⑤→①",
      duties=["공직자 비리·부조리 신고 접수", "공직감찰·도 산하기관 감사"],
      superior="도지사"),

 # 15. 신설 도지사 직속
 dict(sil="AI행정혁신추진단", name="AI행정혁신추진단", sp="SP-DO-AIGOV", level="②",
      duties=["도정 행정서비스 AI 전환", "데이터기반 정책결정 확대", "AI 인재양성"],
      superior="도지사"),
 dict(sil="기본사회추진단", name="기본사회추진단", sp="SP-DO-BASICSOC", level="②",
      duties=["주거·의료·돌봄·교통·에너지 기본사회 정책 기획·조정"],
      superior="도지사"),
 dict(sil="노동안전감독관", name="노동안전감독관", sp="SP-DO-LABOR", level="②",
      duties=["도내 사업장 근로감독(임금체불·최저임금 위반 점검)", "산업재해 예방 감독", "소규모 영세 사업장 집중 감독"],
      superior="도지사"),

 # 16. 그 외
 dict(sil="대변인", name="대변인", sp="SP-DO-SPOKES", level="①",
      duties=["도정 홍보", "언론대응·보도자료"],
      superior="도지사"),
 dict(sil="성평등여성정책관", name="성평등여성정책관", sp="SP-DO-GENDER", level="④",
      duties=["성평등 정책 총괄(과 단위 세분 미작성)"],
      superior="도지사"),
 dict(sil="소방안전본부", name="소방안전본부", sp="SP-AGY-FIRE", level="④",
      duties=["소방·구조·구급 총괄"],
      superior="도지사"),
 dict(sil="도시균형추진단", name="도시균형추진단", sp="SP-DO-BALANCE", level="①",
      duties=["지역균형발전, 원도심·읍면 격차 해소(15분도시)"],
      superior="도지사"),
 dict(sil="강정공동체사업추진단", name="강정공동체사업추진단", sp="SP-DO-GANGJEONG", level="④",
      duties=["강정마을 공동체사업(상세 미검증)"],
      superior="도지사"),
 dict(sil="중앙협력본부", name="중앙협력본부", sp="SP-DO-LIAISON", level="①",
      duties=["국비 확보", "중앙정부 협력"],
      superior="도지사"),
 dict(sil="총무과(보좌기관 계열)", name="총무과(general)", sp="SP-DO-GENERAL", level="④",
      duties=["일반서무, 문서관리, 인사지원(소속 불명확)"],
      superior="행정부지사"),
]

print(len(DEPARTMENTS))
