// division-tables.js
// 과/팀(division) 단위 키워드 라우팅 테이블 — 2026-08-02 재구현
// (직전 세션에서 fix/sp-tree-citizen-routing-gaps 브랜치에 구축 중이던 작업이 push 전
//  크레딧 소진으로 유실되어, prompts/gov-tree/{02-do-dept,04-city}/divisions/ 산하
//  SP 파일들(§0 상위상속 헤더 + §1 정체성 문단)을 다시 파싱해 재생성했다.)
//
// 각 항목: code(SP 코드), 국코드/도메인(상위 부서), 시코드(city만),
// name(과/팀 한글명), desc(LLM 폴백 후보 설명용 — §1 정체성 발췌),
// kw(키워드 매칭용 — 과/팀명 자체 + 정체성 문단에서 추출한 소관 업무 어절),
// file(해당 과/팀 SP 원문 경로, _fetchText 인자로 그대로 사용 가능)

export const CITY_DIVISION_TABLE = [
  { code: "SP-CITYDIV-JEJUSI-CLIMATE-ENVGUIDE", 국코드: "climate", 시코드: "jejusi",
    name: "제주시청 청정환경국 환경지도과", desc: "당신은 **제주시청 청정환경국 환경지도과**를 대표하는 AI 레이어다. 환경오염 단속, 폐기물 배출업소 지도·점검을 담당한다.",
    kw: ["점검", "폐기물 배출업소 지도", "환경오염 단속", "환경지도", "환경지도과"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-CLIMATE-ENVGUIDE_v1.0.md" },
  { code: "SP-CITYDIV-JEJUSI-CLIMATE-ENVMGMT", 국코드: "climate", 시코드: "jejusi",
    name: "제주시청 청정환경국 환경관리과", desc: "당신은 **제주시청 청정환경국 환경관리과**를 대표하는 AI 레이어다. 환경 총괄, 대기·수질 관리를 담당한다 — 도청 기후환경국(SP-DO-CLIMATE)이 도 전체 환경정책·탄소중립을 다루는 것과 달리, 이 과는 관내 환경 인허가·관리 실무를 집행한다.",
    kw: ["대기", "수질 관리", "환경 총괄", "환경관리", "환경관리과"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-CLIMATE-ENVMGMT_v1.1.md" },
  { code: "SP-CITYDIV-JEJUSI-CLIMATE-FACILITY", 국코드: "climate", 시코드: "jejusi",
    name: "제주시청 청정환경국 환경시설관리소", desc: "당신은 **제주시청 청정환경국 환경시설관리소**를 대표하는 AI 레이어다. 생활폐기물 소각·매립시설 운영을 담당한다.",
    kw: ["매립시설 운영", "폐기물 소각", "환경시설", "환경시설관리소"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-CLIMATE-FACILITY_v1.0.md" },
  { code: "SP-CITYDIV-JEJUSI-CLIMATE-JEOLMUL", 국코드: "climate", 시코드: "jejusi",
    name: "제주시청 청정환경국 절물생태관리소", desc: "당신은 **제주시청 청정환경국 절물생태관리소**를 대표하는 AI 레이어다. 절물자연휴양림 운영·관리를 담당한다.",
    kw: ["관리", "절물생태", "절물생태관리소", "절물자연휴양림 운영"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-CLIMATE-JEOLMUL_v1.0.md" },
  { code: "SP-CITYDIV-JEJUSI-CLIMATE-LIVINGENV", 국코드: "climate", 시코드: "jejusi",
    name: "제주시청 청정환경국 생활환경과", desc: "당신은 **제주시청 청정환경국 생활환경과**를 대표하는 AI 레이어다. 생활폐기물 수거, 재활용 정책을 담당한다.",
    kw: ["생활환경", "생활환경과", "재활용 정책", "폐기물 수거"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-CLIMATE-LIVINGENV_v1.0.md" },
  { code: "SP-CITYDIV-JEJUSI-CLIMATE-PARKS", 국코드: "climate", 시코드: "jejusi",
    name: "제주시청 청정환경국 공원녹지과", desc: "당신은 **제주시청 청정환경국 공원녹지과**를 대표하는 AI 레이어다. 도시공원·가로수 관리를 담당한다.",
    kw: ["가로수 관리", "공원녹지", "공원녹지과", "도시공원"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-CLIMATE-PARKS_v1.1.md" },
  { code: "SP-CITYDIV-JEJUSI-CULTURE-ARTCENTER", 국코드: "culture", 시코드: "jejusi",
    name: "제주시청 문화관광체육국 제주아트센터", desc: "당신은 **제주시청 문화관광체육국 제주아트센터**를 대표하는 AI 레이어다. 제주아트센터 공연장 운영·대관을 담당한다.",
    kw: ["대관", "제주아트", "제주아트센터", "제주아트센터 공연장 운영"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-CULTURE-ARTCENTER_v1.0.md" },
  { code: "SP-CITYDIV-JEJUSI-CULTURE-ART", 국코드: "culture", 시코드: "jejusi",
    name: "제주시청 문화관광체육국 문화예술과", desc: "당신은 **제주시청 문화관광체육국 문화예술과**를 대표하는 AI 레이어다. 문화예술 지원사업, 공연·전시 행정을 담당한다.",
    kw: ["공연", "문화예술", "문화예술 지원사업", "문화예술과", "전시 행정"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-CULTURE-ART_v1.0.md" },
  { code: "SP-CITYDIV-JEJUSI-CULTURE-SPORTS", 국코드: "culture", 시코드: "jejusi",
    name: "제주시청 문화관광체육국 체육진흥과", desc: "당신은 **제주시청 문화관광체육국 체육진흥과**를 대표하는 AI 레이어다. 생활체육 진흥, 공공체육시설 관리를 담당한다.",
    kw: ["공공체육시설 관리", "체육 진흥", "체육진흥", "체육진흥과"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-CULTURE-SPORTS_v1.0.md" },
  { code: "SP-CITYDIV-JEJUSI-CULTURE-TAMNALIB", 국코드: "culture", 시코드: "jejusi",
    name: "제주시청 문화관광체육국 탐라도서관", desc: "당신은 **제주시청 문화관광체육국 탐라도서관**를 대표하는 AI 레이어다. 제주시립 탐라도서관 — 도서 대출·반납, 자료실 이용을 담당하는 공공도서관이다.",
    kw: ["제주시립 탐라도서관", "탐라도서관"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-CULTURE-TAMNALIB_v1.0.md" },
  { code: "SP-CITYDIV-JEJUSI-CULTURE-TOURISM", 국코드: "culture", 시코드: "jejusi",
    name: "제주시청 문화관광체육국 관광진흥과", desc: "당신은 **제주시청 문화관광체육국 관광진흥과**를 대표하는 AI 레이어다. 관광사업체 등록, 관광안내소 운영을 담당한다 — 도청 관광교류국(SP-DO-TOURISM)이 도 전체 관광정책·해외마케팅을 다루는 것과 달리, 이 과는 관내 관광사업체 개별 등록·안내소 운영 실무를 담당한다.",
    kw: ["관광사업체 등록", "관광안내소 운영", "관광진흥", "관광진흥과"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-CULTURE-TOURISM_v1.1.md" },
  { code: "SP-CITYDIV-JEJUSI-CULTURE-UDANGLIB", 국코드: "culture", 시코드: "jejusi",
    name: "제주시청 문화관광체육국 우당도서관", desc: "당신은 **제주시청 문화관광체육국 우당도서관**를 대표하는 AI 레이어다. 제주시립 우당도서관 — 도서 대출·반납, 자료실 이용을 담당하는 공공도서관이다.",
    kw: ["우당도서관", "제주시립 우당도서관"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-CULTURE-UDANGLIB_v1.0.md" },
  { code: "SP-CITYDIV-JEJUSI-ECON-INFOSUPPORT", 국코드: "econ", 시코드: "jejusi",
    name: "제주시청 경제일자리국 정보화지원과", desc: "당신은 **제주시청 경제일자리국 정보화지원과**를 대표하는 AI 레이어다. 정보화교육, 스마트시티 관련 사업을 담당한다.",
    kw: ["스마트시티 관련 사업", "정보화교육", "정보화지원", "정보화지원과"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-ECON-INFOSUPPORT_v1.0.md" },
  { code: "SP-CITYDIV-JEJUSI-ECON-JOBENERGY", 국코드: "econ", 시코드: "jejusi",
    name: "제주시청 경제일자리국 일자리에너지과", desc: "당신은 **제주시청 경제일자리국 일자리에너지과**를 대표하는 AI 레이어다. 공공일자리사업, 에너지 절약·신재생에너지 보급 지원을 담당한다.",
    kw: ["공공일자리사업", "신재생에너지 보급 지원", "에너지 절약", "일자리에너지", "일자리에너지과"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-ECON-JOBENERGY_v1.0.md" },
  { code: "SP-CITYDIV-JEJUSI-ECON-SMB", 국코드: "econ", 시코드: "jejusi",
    name: "제주시청 경제일자리국 경제소상공인과", desc: "당신은 **제주시청 경제일자리국 경제소상공인과**를 대표하는 AI 레이어다. 소상공인 지원, 전통시장 활성화를 담당한다 — 도청 경제활력국(SP-DO-ECON)이 도 전체 산업정책을 다루는 것과 달리, 이 과는 제주시 관내 소상공인 개별 지원사업을 집행한다.",
    kw: ["경제소상공인", "경제소상공인과", "소상공인 지원", "전통시장 활성화"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-ECON-SMB_v1.0.md" },
  { code: "SP-CITYDIV-JEJUSI-ECON-VILLAGE", 국코드: "econ", 시코드: "jejusi",
    name: "제주시청 경제일자리국 마을활력과", desc: "당신은 **제주시청 경제일자리국 마을활력과**를 대표하는 AI 레이어다. 마을만들기, 주민 주도 도시재생 사업을 담당한다 — 자치행정과(SELFGOV)의 '읍면동 행정 총괄·주민자치'와 이름이 유사해 보이지만, 이 과는 마을 단위 물리적·경제적 활력사업(마을기업, 도시재생 등)을 집행하고 자치행정과는 읍면동 행정지원·주민자치위원회 운영을 담당한다는 점에서 ",
    kw: ["마을만들기", "마을활력", "마을활력과", "주민 주도 도시재생 사업"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-ECON-VILLAGE_v1.1.md" },
  { code: "SP-CITYDIV-JEJUSI-JACHI-BASICGOVPREP", 국코드: "jachi", 시코드: "jejusi",
    name: "제주시청 자치행정국 기초자치단체 설치준비지원단", desc: "당신은 **제주시청 자치행정국 기초자치단체 설치준비지원단**을 대표하는 AI 레이어다.",
    kw: ["설치준비지원단"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-JACHI-BASICGOVPREP_v1.2.md" },
  { code: "SP-CITYDIV-JEJUSI-JACHI-BUDGET", 국코드: "jachi", 시코드: "jejusi",
    name: "제주시청 자치행정국 기획예산과", desc: "당신은 **제주시청 자치행정국 기획예산과**를 대표하는 AI 레이어다. 시정 전반의 기획·예산편성·조직관리를 담당하며, 도청 기획조정실(SP-DO-PLAN)의 시청 축소판에 가깝다 — 단, 시는 독자 예산편성권이 도 예산틀 안에 있어 도청과 관계가 더 밀접하다.",
    kw: ["기획예산", "기획예산과", "시정 전반의 기획", "예산편성", "조직관리를 담당하며"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-JACHI-BUDGET_v1.2.md" },
  { code: "SP-CITYDIV-JEJUSI-JACHI-GENERAL", 국코드: "jachi", 시코드: "jejusi",
    name: "제주시청 자치행정국 총무과", desc: "당신은 **제주시청 자치행정국 총무과**를 대표하는 AI 레이어다. 도청 실·국 계층의 총무과(예: SP-DIV-JACHI-GENERAL)와 성격이 유사하다 — 시민을 직접 상대하기보다 시청 내부 행정(문서·인사·의전·청사관리)을 지원한다.",
    kw: ["국 계층의 총무과와 성격이 유사하다", "도청 실", "총무", "총무과"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-JACHI-GENERAL_v1.2.md" },
  { code: "SP-CITYDIV-JEJUSI-JACHI-PROPERTYTAX", 국코드: "jachi", 시코드: "jejusi",
    name: "제주시청 자치행정국 재산세과", desc: "당신은 **제주시청 자치행정국 재산세과**를 대표하는 AI 레이어다. 재산세·자동차세 등 시청이 매년 정기적으로 부과(고지)하는 지방세를 담당한다 — **취득·등록 시 신고하는 세목(취득세 등)은 세무과 소관이므로 혼동하지 않는다.**",
    kw: ["재산세", "재산세과"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-JACHI-PROPERTYTAX_v1.2.md" },
  { code: "SP-CITYDIV-JEJUSI-JACHI-SELFGOV", 국코드: "jachi", 시코드: "jejusi",
    name: "제주시청 자치행정국 자치행정과", desc: "당신은 **제주시청 자치행정국 자치행정과**를 대표하는 AI 레이어다. 읍면동 행정 총괄·지원, 주민자치·마을공동체 관련 업무, 선거 관련 행정지원(선거관리위원회와는 별개 기관)을 담당한다.",
    kw: ["마을공동체 관련 업무", "선거 관련 행정지원", "읍면동 행정 총괄", "자치행정", "자치행정과", "주민자치", "지원"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-JACHI-SELFGOV_v1.2.md" },
  { code: "SP-CITYDIV-JEJUSI-JACHI-TAX", 국코드: "jachi", 시코드: "jejusi",
    name: "제주시청 자치행정국 세무과", desc: "당신은 **제주시청 자치행정국 세무과**를 대표하는 AI 레이어다. 취득세·등록면허세·지방소득세 등 신고납부형 지방세를 담당한다 — **재산세·자동차세 등 부과형 지방세는 재산세과(별도 과) 소관이므로 혼동하지 않는다.**",
    kw: ["등록면허세", "세무", "세무과", "지방소득세 등 신고납부형 지방세", "취득세"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-JACHI-TAX_v1.3.md" },
  { code: "SP-CITYDIV-JEJUSI-SAFETY-GENERAL", 국코드: "safety", 시코드: "jejusi",
    name: "제주시청 안전교통국 안전총괄과", desc: "당신은 **제주시청 안전교통국 안전총괄과**를 대표하는 AI 레이어다. 재난안전대책본부 운영, 민방위, 자연·사회재난 대응을 총괄한다 — 도청 도민안전건강실(SP-DO-SAFETY)이 도 전체 재난정책을 다루는 것과 달리, 이 과는 제주시 관내 현장 대응·재난안전대책본부 실무를 담당한다.",
    kw: ["민방위", "사회재난 대응을 총괄한다", "안전총괄", "안전총괄과", "자연", "재난안전대책본부 운영"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-SAFETY-GENERAL_v1.1.md" },
  { code: "SP-CITYDIV-JEJUSI-SAFETY-TRAFFIC", 국코드: "safety", 시코드: "jejusi",
    name: "제주시청 안전교통국 교통행정과", desc: "당신은 **제주시청 안전교통국 교통행정과**를 대표하는 AI 레이어다. 제주시 관내 시내버스·택시 등 여객자동차운송사업 인허가, 교통안전시설물(신호등·표지판) 관리 실무를 담당한다 — 도청 교통항공국(SP-DO-TRANSPORT)이 도 전체 대중교통 정책·요금체계를 다루는 것과 달리, 이 과는 관내 개별 인허가·시설 실무를 처리한다.",
    kw: ["교통안전시설물 관리 실무", "교통행정", "교통행정과", "제주시 관내 시내버스", "택시 등 여객자동차운송사업 인허가"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-SAFETY-TRAFFIC_v1.1.md" },
  { code: "SP-CITYDIV-JEJUSI-SAFETY-VEHICLE", 국코드: "safety", 시코드: "jejusi",
    name: "제주시청 안전교통국 차량관리과", desc: "당신은 **제주시청 안전교통국 차량관리과**를 대표하는 AI 레이어다. 자동차 등록·이전등록, 차고지증명제 운영을 담당한다.",
    kw: ["이전등록", "자동차 등록", "차고지증명제 운영", "차량관리", "차량관리과"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-SAFETY-VEHICLE_v1.1.md" },
  { code: "SP-CITYDIV-JEJUSI-WELFARE-BASICLIVELIHOOD", 국코드: "welfare", 시코드: "jejusi",
    name: "제주시청 복지위생국 기초생활보장과", desc: "당신은 **제주시청 복지위생국 기초생활보장과**를 대표하는 AI 레이어다. 국민기초생활보장(생계·의료·주거·교육급여) 신청·조사를 담당한다.",
    kw: ["국민기초생활보장 신청", "기초생활보장", "기초생활보장과", "조사"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-WELFARE-BASICLIVELIHOOD_v1.1.md" },
  { code: "SP-CITYDIV-JEJUSI-WELFARE-DISABLED", 국코드: "welfare", 시코드: "jejusi",
    name: "제주시청 복지위생국 장애인복지과", desc: "당신은 **제주시청 복지위생국 장애인복지과**를 대표하는 AI 레이어다. 장애인 등록, 장애수당·장애인연금, 장애인 활동지원 신청을 담당한다.",
    kw: ["장애수당", "장애인 등록", "장애인 활동지원 신청", "장애인복지", "장애인복지과", "장애인연금"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-WELFARE-DISABLED_v1.1.md" },
  { code: "SP-CITYDIV-JEJUSI-WELFARE-ELDERLY", 국코드: "welfare", 시코드: "jejusi",
    name: "제주시청 복지위생국 노인복지과", desc: "당신은 **제주시청 복지위생국 노인복지과**를 대표하는 AI 레이어다. 기초연금, 노인일자리, 경로당 지원을 담당한다.",
    kw: ["경로당 지원", "기초연금", "노인복지", "노인복지과", "노인일자리"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-WELFARE-ELDERLY_v1.1.md" },
  { code: "SP-CITYDIV-JEJUSI-WELFARE-HYGIENE", 국코드: "welfare", 시코드: "jejusi",
    name: "제주시청 복지위생국 위생관리과", desc: "당신은 **제주시청 복지위생국 위생관리과**를 대표하는 AI 레이어다. 식품위생업소(음식점 등) 및 공중위생업(숙박·미용 등) 인허가·신고를 담당한다.",
    kw: ["공중위생업 인허가", "식품위생업소", "신고", "위생관리", "위생관리과"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-WELFARE-HYGIENE_v1.1.md" },
  { code: "SP-CITYDIV-JEJUSI-WELFARE-RESIDENT", 국코드: "welfare", 시코드: "jejusi",
    name: "제주시청 복지위생국 주민복지과", desc: "당신은 **제주시청 복지위생국 주민복지과**를 대표하는 AI 레이어다. 복지 총괄·긴급복지지원·사회보장급여 총괄 조정을 담당한다 — 도청 복지가족국(SP-DO-WELFARE)이 도 전체 복지정책을 수립하는 것과 달리, 이 과는 제주시 관내 개별 신청·급여 실행을 담당한다.",
    kw: ["긴급복지지원", "복지 총괄", "사회보장급여 총괄 조정", "주민복지", "주민복지과"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-WELFARE-RESIDENT_v1.1.md" },
  { code: "SP-CITYDIV-JEJUSI-WELFARE-WOMENFAMILY", 국코드: "welfare", 시코드: "jejusi",
    name: "제주시청 복지위생국 여성가족과", desc: "당신은 **제주시청 복지위생국 여성가족과**를 대표하는 AI 레이어다. 한부모가족 지원, 가정폭력·성폭력 피해자 보호, 여성긴급전화 연계를 담당한다.",
    kw: ["가정폭력", "성폭력 피해자 보호", "여성가족", "여성가족과", "여성긴급전화 연계", "한부모가족 지원"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-WELFARE-WOMENFAMILY_v1.1.md" },
  { code: "SP-CITYDIV-JEJUSI-URBANCONSTRUCTION-CITYPLAN", 국코드: "urbanconstruction", 시코드: "jejusi",
    name: "제주시청 도시건설국 도시계획과", desc: "당신은 **제주시청 도시건설국 도시계획과**를 대표하는 AI 레이어다. 도시계획 수립·관리, 용도지역 지정, 도시관리계획 변경을 담당한다 — 서귀포시청 안전도시건설국 도시과(SP-CITYDIV-SEOGWIPO-CONSTRUCTION-CITY)에 대응하나, 제주시는 도시계획과 도시재생을 별개 과로 분리 운영한다.",
    kw: ["도시계획", "도시계획과", "용도지역", "도시관리계획", "지구단위계획"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-URBANCONSTRUCTION-CITYPLAN_v1.0.md" },
  { code: "SP-CITYDIV-JEJUSI-URBANCONSTRUCTION-REGEN", 국코드: "urbanconstruction", 시코드: "jejusi",
    name: "제주시청 도시건설국 도시재생과", desc: "당신은 **제주시청 도시건설국 도시재생과**를 대표하는 AI 레이어다. 도시재생 뉴딜사업, 원도심 활성화, 주거환경개선사업을 담당한다.",
    kw: ["도시재생", "도시재생과", "원도심 활성화", "주거환경개선사업", "뉴딜사업"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-URBANCONSTRUCTION-REGEN_v1.0.md" },
  { code: "SP-CITYDIV-JEJUSI-URBANCONSTRUCTION-CONSTRUCT", 국코드: "urbanconstruction", 시코드: "jejusi",
    name: "제주시청 도시건설국 건설과", desc: "당신은 **제주시청 도시건설국 건설과**를 대표하는 AI 레이어다. 도로·하천 등 토목시설 건설·관리, 도로점용허가를 담당한다 — 서귀포시청 건설과(SP-CITYDIV-SEOGWIPO-CONSTRUCTION-CONSTRUCT)에 대응한다.",
    kw: ["건설", "건설과", "도로점용허가", "도로 파손", "토목시설"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-URBANCONSTRUCTION-CONSTRUCT_v1.0.md" },
  { code: "SP-CITYDIV-JEJUSI-URBANCONSTRUCTION-HOUSING", 국코드: "urbanconstruction", 시코드: "jejusi",
    name: "제주시청 도시건설국 주택과", desc: "당신은 **제주시청 도시건설국 주택과**를 대표하는 AI 레이어다. 주택사업계획승인, 공동주택 관리, 임대주택 정책을 담당한다 — 서귀포시청 CONSTRUCTION 계열에는 대응 과가 확인되지 않아 제주시 단독 부서로 잠정 처리한다.",
    kw: ["주택", "주택과", "주택사업계획승인", "공동주택 관리", "임대주택"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-URBANCONSTRUCTION-HOUSING_v1.0.md" },
  { code: "SP-CITYDIV-JEJUSI-URBANCONSTRUCTION-BUILDING", 국코드: "urbanconstruction", 시코드: "jejusi",
    name: "제주시청 도시건설국 건축과", desc: "당신은 **제주시청 도시건설국 건축과**를 대표하는 AI 레이어다. 건축 인허가, 건축물 안전점검, 사용승인(준공검사)을 담당한다 — 서귀포시청 안전도시건설국 건축과(SP-CITYDIV-SEOGWIPO-CONSTRUCTION-BUILDING)와 동일 업무를 제주시 관내에서 수행한다.",
    kw: ["건축", "건축 인허가", "건축과", "건축물 안전점검", "사용승인", "준공검사"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-URBANCONSTRUCTION-BUILDING_v1.0.md" },
  { code: "SP-CITYDIV-JEJUSI-URBANCONSTRUCTION-WATER", 국코드: "urbanconstruction", 시코드: "jejusi",
    name: "제주시청 도시건설국 상하수도과", desc: "당신은 **제주시청 도시건설국 상하수도과**를 대표하는 AI 레이어다. 상수도·하수도 시설 관리, 급수·배수 민원, 상하수도 신설·철거 공사 승인을 담당한다. ★ 도청 직속 상하수도본부(SP-AGY-WATER)와의 관할 경계는 재확인 필요.",
    kw: ["급수", "배수 민원", "상수도", "상하수도", "상하수도과", "하수도 시설 관리"], file: "04-city/divisions/SP-CITYDIV-JEJUSI-URBANCONSTRUCTION-WATER_v1.1.md" },
  { code: "SP-CITYDIV-SEOGWIPO-AGRIECONOMY-CITRUS", 국코드: "agrieconomy", 시코드: "seogwipo",
    name: "서귀포시청 농수축산경제국 감귤유통과", desc: "당신은 **서귀포시청 농수축산경제국 감귤유통과**를 대표하는 AI 레이어다. 감귤 유통·가격안정, 감귤 관련 조례 집행을 담당한다 — 제주 감귤 산업 특성상 이 과는 서귀포시(제주 최대 감귤 주산지)에만 있는 특화 부서로 확인된다.",
    kw: ["가격안정", "감귤 관련 조례 집행", "감귤 유통", "감귤유통", "감귤유통과"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-AGRIECONOMY-CITRUS_v1.0.md" },
  { code: "SP-CITYDIV-SEOGWIPO-AGRIECONOMY-DIGITAL", 국코드: "agrieconomy", 시코드: "seogwipo",
    name: "서귀포시청 농수축산경제국 디지털혁신과", desc: "당신은 **서귀포시청 농수축산경제국 디지털혁신과**를 대표하는 AI 레이어다. 지역 디지털 전환·정보화 지원을 담당한다 — 제주시 정보화지원과(경제일자리국 산하)에 대응하는 서귀포시 부서로 추정된다.",
    kw: ["디지털혁신", "디지털혁신과", "정보화 지원", "지역 디지털 전환"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-AGRIECONOMY-DIGITAL_v1.0.md" },
  { code: "SP-CITYDIV-SEOGWIPO-AGRIECONOMY-ECOFARM", 국코드: "agrieconomy", 시코드: "seogwipo",
    name: "서귀포시청 농수축산경제국 친환경농정과", desc: "당신은 **서귀포시청 농수축산경제국 친환경농정과**를 대표하는 AI 레이어다. 친환경농업 인증·지원, 일반 농정을 담당한다.",
    kw: ["일반 농정", "지원", "친환경농업 인증", "친환경농정", "친환경농정과"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-AGRIECONOMY-ECOFARM_v1.0.md" },
  { code: "SP-CITYDIV-SEOGWIPO-AGRIECONOMY-FISHERY", 국코드: "agrieconomy", 시코드: "seogwipo",
    name: "서귀포시청 농수축산경제국 해양수산과", desc: "당신은 **서귀포시청 농수축산경제국 해양수산과**를 대표하는 AI 레이어다. 어업 면허·허가, 수산물 유통을 담당한다 — 도청 해양수산국(SP-DO-OCEAN)이 도 전체 어업 정책·국가관리항만을 다루는 것과 달리, 이 과는 관내 개별 어업면허·수산업 인허가를 담당한다.",
    kw: ["수산물 유통", "어업 면허", "해양수산", "해양수산과", "허가"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-AGRIECONOMY-FISHERY_v1.1.md" },
  { code: "SP-CITYDIV-SEOGWIPO-AGRIECONOMY-JOBS", 국코드: "agrieconomy", 시코드: "seogwipo",
    name: "서귀포시청 농수축산경제국 경제일자리과", desc: "당신은 **서귀포시청 농수축산경제국 경제일자리과**를 대표하는 AI 레이어다. 소상공인 지원, 일자리 정책을 담당한다 — 제주시의 경제소상공인과·일자리에너지과(경제일자리국 산하)에 해당하는 업무를 서귀포시는 이 국 안의 한 과가 통합 담당하는 것으로 확인된다.",
    kw: ["경제일자리", "경제일자리과", "소상공인 지원", "일자리 정책"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-AGRIECONOMY-JOBS_v1.0.md" },
  { code: "SP-CITYDIV-SEOGWIPO-AGRIECONOMY-LIVESTOCK", 국코드: "agrieconomy", 시코드: "seogwipo",
    name: "서귀포시청 농수축산경제국 청정축산과", desc: "당신은 **서귀포시청 농수축산경제국 청정축산과**를 대표하는 AI 레이어다. 축산업 허가·신고, 가축분뇨 관리, 동물방역을 담당한다.",
    kw: ["가축분뇨 관리", "동물방역", "신고", "청정축산", "청정축산과", "축산업 허가"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-AGRIECONOMY-LIVESTOCK_v1.1.md" },
  { code: "SP-CITYDIV-SEOGWIPO-CLIMATE-ENVMGMT", 국코드: "climate", 시코드: "seogwipo",
    name: "서귀포시청 청정환경국 기후환경과", desc: "당신은 **서귀포시청 청정환경국 기후환경과**를 대표하는 AI 레이어다. 환경 총괄, 대기·수질 관리, 기후 관련 인허가를 담당한다 — 제주시의 동명 국(局) 산하 환경관리과·환경지도과 2개 과 업무를 서귀포시는 이 과 하나가 통합 담당하는 것으로 추정된다.",
    kw: ["기후 관련 인허가", "기후환경", "기후환경과", "대기", "수질 관리", "환경 총괄"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-CLIMATE-ENVMGMT_v1.1.md" },
  { code: "SP-CITYDIV-SEOGWIPO-CLIMATE-FORESTRECREATION", 국코드: "climate", 시코드: "seogwipo",
    name: "서귀포시청 청정환경국 산림휴양관리소", desc: "당신은 **서귀포시청 청정환경국 산림휴양관리소**를 대표하는 AI 레이어다. 서귀포시 관내 산림휴양시설(휴양림·숲길 등) 운영·관리를 담당한다 — 제주시 절물생태관리소(SP-CITYDIV-JEJUSI-CLIMATE-JEOLMUL)에 대응하는 서귀포시 시설이다.",
    kw: ["관리", "산림휴양", "산림휴양관리소", "서귀포시 관내 산림휴양시설 운영"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-CLIMATE-FORESTRECREATION_v1.0.md" },
  { code: "SP-CITYDIV-SEOGWIPO-CLIMATE-LIVINGENV", 국코드: "climate", 시코드: "seogwipo",
    name: "서귀포시청 청정환경국 생활환경과", desc: "당신은 **서귀포시청 청정환경국 생활환경과**를 대표하는 AI 레이어다. 생활폐기물 수거, 재활용 정책을 담당한다.",
    kw: ["생활환경", "생활환경과", "재활용 정책", "폐기물 수거"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-CLIMATE-LIVINGENV_v1.0.md" },
  { code: "SP-CITYDIV-SEOGWIPO-CLIMATE-PARKS", 국코드: "climate", 시코드: "seogwipo",
    name: "서귀포시청 청정환경국 공원녹지과", desc: "당신은 **서귀포시청 청정환경국 공원녹지과**를 대표하는 AI 레이어다. 도시공원·가로수 관리를 담당한다.",
    kw: ["가로수 관리", "공원녹지", "공원녹지과", "도시공원"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-CLIMATE-PARKS_v1.1.md" },
  { code: "SP-CITYDIV-SEOGWIPO-CONSTRUCTION-BUILDING", 국코드: "housing", 시코드: "seogwipo",
    name: "서귀포시청 안전도시건설국 건축과", desc: "당신은 **서귀포시청 안전도시건설국 건축과**를 대표하는 AI 레이어다. 건축 인허가, 건축물 안전점검을 담당한다.",
    kw: ["건축", "건축 인허가", "건축과", "건축물 안전점검"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-CONSTRUCTION-BUILDING_v1.3.md" },
  { code: "SP-CITYDIV-SEOGWIPO-CONSTRUCTION-CITY", 국코드: "housing", 시코드: "seogwipo",
    name: "서귀포시청 안전도시건설국 도시과", desc: "당신은 **서귀포시청 안전도시건설국 도시과**를 대표하는 AI 레이어다. 도시계획, 도시재생 행정을 담당한다.",
    kw: ["도시", "도시계획", "도시과", "도시재생 행정"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-CONSTRUCTION-CITY_v1.1.md" },
  { code: "SP-CITYDIV-SEOGWIPO-CONSTRUCTION-CONSTRUCT", 국코드: "housing", 시코드: "seogwipo",
    name: "서귀포시청 안전도시건설국 건설과", desc: "당신은 **서귀포시청 안전도시건설국 건설과**를 대표하는 AI 레이어다. 도로·하천 등 토목시설 건설·관리를 담당한다.",
    kw: ["건설", "건설과", "관리", "도로", "하천 등 토목시설 건설"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-CONSTRUCTION-CONSTRUCT_v1.1.md" },
  { code: "SP-CITYDIV-SEOGWIPO-CONSTRUCTION-GENERAL", 국코드: "housing", 시코드: "seogwipo",
    name: "서귀포시청 안전도시건설국 안전총괄과", desc: "당신은 **서귀포시청 안전도시건설국 안전총괄과**를 대표하는 AI 레이어다. 재난안전대책본부 운영, 민방위, 자연·사회재난 대응을 총괄한다 — 제주시 안전교통국 안전총괄과(SP-CITYDIV-JEJUSI-SAFETY-GENERAL)에 대응하며, 도청 도민안전건강실(SP-DO-SAFETY)과는 정책 vs 현장 대응으로 구분된다.",
    kw: ["민방위", "사회재난 대응을 총괄한다", "안전총괄", "안전총괄과", "자연", "재난안전대책본부 운영"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-CONSTRUCTION-GENERAL_v1.1.md" },
  { code: "SP-CITYDIV-SEOGWIPO-CONSTRUCTION-TRAFFIC", 국코드: "housing", 시코드: "seogwipo",
    name: "서귀포시청 안전도시건설국 교통행정과", desc: "당신은 **서귀포시청 안전도시건설국 교통행정과**를 대표하는 AI 레이어다. 여객자동차운송사업 인허가, 교통안전시설물 관리를 담당한다 — 제주시 안전교통국 교통행정과(SP-CITYDIV-JEJUSI-SAFETY-TRAFFIC)에 대응하나, 서귀포시는 이 업무가 안전총괄과와 별개로 안전도시건설국 산하에 있다는 점에서 소속 국 구조가 제주시와 다르지 않다(둘 ",
    kw: ["교통안전시설물 관리", "교통행정", "교통행정과", "여객자동차운송사업 인허가"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-CONSTRUCTION-TRAFFIC_v1.1.md" },
  { code: "SP-CITYDIV-SEOGWIPO-CONSTRUCTION-WATER", 국코드: "housing", 시코드: "seogwipo",
    name: "서귀포시청 안전도시건설국 상하수도과", desc: "당신은 **서귀포시청 안전도시건설국 상하수도과**를 대표하는 AI 레이어다. 상수도·하수도 시설 관리, 급수·배수 민원을 담당한다.",
    kw: ["급수", "배수 민원", "상수도", "상하수도", "상하수도과", "하수도 시설 관리"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-CONSTRUCTION-WATER_v1.2.md" },
  { code: "SP-CITYDIV-SEOGWIPO-CULTURE-ARTMUSEUM", 국코드: "culture", 시코드: "seogwipo",
    name: "서귀포시청 문화관광체육국 서귀포 공립미술관", desc: "당신은 **서귀포시청 문화관광체육국 서귀포 공립미술관**를 대표하는 AI 레이어다. 서귀포시 공립미술관 운영·전시를 담당한다.",
    kw: ["공립미술관", "서귀포시 공립미술관 운영", "전시"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-CULTURE-ARTMUSEUM_v1.0.md" },
  { code: "SP-CITYDIV-SEOGWIPO-CULTURE-ARTSHALL", 국코드: "culture", 시코드: "seogwipo",
    name: "서귀포시청 문화관광체육국 서귀포예술의전당", desc: "당신은 **서귀포시청 문화관광체육국 서귀포예술의전당**를 대표하는 AI 레이어다. 서귀포예술의전당 공연장 운영·대관을 담당한다 — 제주시 제주아트센터(SP-CITYDIV-JEJUSI-CULTURE-ARTCENTER)에 대응하는 서귀포시 공연시설이다.",
    kw: ["대관", "서귀포예술의전당", "서귀포예술의전당 공연장 운영"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-CULTURE-ARTSHALL_v1.0.md" },
  { code: "SP-CITYDIV-SEOGWIPO-CULTURE-ART", 국코드: "culture", 시코드: "seogwipo",
    name: "서귀포시청 문화관광체육국 문화예술과", desc: "당신은 **서귀포시청 문화관광체육국 문화예술과**를 대표하는 AI 레이어다. 문화예술 지원사업 행정을 담당한다.",
    kw: ["문화예술", "문화예술 지원사업 행정", "문화예술과"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-CULTURE-ART_v1.0.md" },
  { code: "SP-CITYDIV-SEOGWIPO-CULTURE-LIBRARYMGMT", 국코드: "culture", 시코드: "seogwipo",
    name: "서귀포시청 문화관광체육국 도서관운영사무소", desc: "당신은 **서귀포시청 문화관광체육국 도서관운영사무소**를 대표하는 AI 레이어다. 서귀포시 관내 공공도서관 운영을 총괄한다 — 제주시가 도서관마다 개별 부서(우당·탐라)로 관리하는 것과 달리, 서귀포시는 하나의 사무소가 여러 도서관을 총괄하는 구조로 확인된다(2026-07-13 시점, 개별 도서관명은 재확인 필요).",
    kw: ["도서관운영", "도서관운영사무소"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-CULTURE-LIBRARYMGMT_v1.0.md" },
  { code: "SP-CITYDIV-SEOGWIPO-CULTURE-SPORTS", 국코드: "culture", 시코드: "seogwipo",
    name: "서귀포시청 문화관광체육국 체육진흥과", desc: "당신은 **서귀포시청 문화관광체육국 체육진흥과**를 대표하는 AI 레이어다. 생활체육 진흥, 공공체육시설 관리를 담당한다.",
    kw: ["공공체육시설 관리", "체육 진흥", "체육진흥", "체육진흥과"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-CULTURE-SPORTS_v1.0.md" },
  { code: "SP-CITYDIV-SEOGWIPO-CULTURE-TOURISMFACILITY", 국코드: "culture", 시코드: "seogwipo",
    name: "서귀포시청 문화관광체육국 관광지관리소", desc: "당신은 **서귀포시청 문화관광체육국 관광지관리소**를 대표하는 AI 레이어다. 서귀포시 관내 공공 관광지(전망대·공원형 관광지 등) 시설 관리를 담당한다.",
    kw: ["관광지", "관광지관리소", "서귀포시 관내 공공 관광지 시설 관리"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-CULTURE-TOURISMFACILITY_v1.0.md" },
  { code: "SP-CITYDIV-SEOGWIPO-CULTURE-TOURISM", 국코드: "culture", 시코드: "seogwipo",
    name: "서귀포시청 문화관광체육국 관광진흥과", desc: "당신은 **서귀포시청 문화관광체육국 관광진흥과**를 대표하는 AI 레이어다. 관광사업체 등록을 담당한다 — 도청 관광교류국(SP-DO-TOURISM)의 정책·해외마케팅과 구분된다.",
    kw: ["관광사업체 등록", "관광진흥", "관광진흥과"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-CULTURE-TOURISM_v1.1.md" },
  { code: "SP-CITYDIV-SEOGWIPO-HEALTH-ADMIN", 국코드: "health", 시코드: "seogwipo",
    name: "서귀포시청 서귀포보건소 보건행정과", desc: "당신은 **서귀포시청 서귀포보건소 보건행정과**를 대표하는 AI 레이어다. 보건소 행정 총괄, 의료기관 인허가를 담당한다.",
    kw: ["보건소 행정 총괄", "보건행정", "보건행정과", "의료기관 인허가"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-HEALTH-ADMIN_v1.1.md" },
  { code: "SP-CITYDIV-SEOGWIPO-HEALTH-EASTCENTER", 국코드: "health", 시코드: "seogwipo",
    name: "서귀포시청 서귀포보건소 동부보건소", desc: "당신은 **서귀포시청 서귀포보건소 동부보건소**를 대표하는 AI 레이어다. 서귀포시 동부지역 관할 보건지소 — 예방접종·건강검진 등 보건소 기능을 지역 분산 수행한다.",
    kw: ["동부보건", "동부보건소", "서귀포시 동부지역 관할 보건지소"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-HEALTH-EASTCENTER_v1.0.md" },
  { code: "SP-CITYDIV-SEOGWIPO-HEALTH-PROMOTION", 국코드: "health", 시코드: "seogwipo",
    name: "서귀포시청 서귀포보건소 건강증진과", desc: "당신은 **서귀포시청 서귀포보건소 건강증진과**를 대표하는 AI 레이어다. 예방접종, 건강검진, 만성질환 관리사업을 담당한다.",
    kw: ["건강검진", "건강증진", "건강증진과", "만성질환 관리사업", "예방접종"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-HEALTH-PROMOTION_v1.0.md" },
  { code: "SP-CITYDIV-SEOGWIPO-HEALTH-WESTCENTER", 국코드: "health", 시코드: "seogwipo",
    name: "서귀포시청 서귀포보건소 서부보건소", desc: "당신은 **서귀포시청 서귀포보건소 서부보건소**를 대표하는 AI 레이어다. 서귀포시 서부지역 관할 보건지소 — 예방접종·건강검진 등 보건소 기능을 지역 분산 수행한다.",
    kw: ["서귀포시 서부지역 관할 보건지소", "서부보건", "서부보건소"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-HEALTH-WESTCENTER_v1.0.md" },
  { code: "SP-CITYDIV-SEOGWIPO-JACHI-BASICGOVPREP", 국코드: "jachi", 시코드: "seogwipo",
    name: "서귀포시청 자치행정국 기초자치단체설치준비지원단", desc: "당신은 **서귀포시청 자치행정국 기초자치단체설치준비지원단**를 대표하는 AI 레이어다. 기초자치단체(시·군 등 법인격 있는 기초지자체) 부활·도입 준비를 위해 설치됐다 — **제주시의 동일 명칭 부서(SP-CITYDIV-JEJUSI-JACHI-BASICGOVPREP)와 동일한 사정을 공유한다**: 민선9기 위성곤 도정이 기초자치단체 도입을 사실상 추진하지 ",
    kw: ["기초자치단체 부활", "기초자치단체설치준비지원단", "도입 준비를 위해 설치됐다"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-JACHI-BASICGOVPREP_v1.0.md" },
  { code: "SP-CITYDIV-SEOGWIPO-JACHI-BUDGET", 국코드: "jachi", 시코드: "seogwipo",
    name: "서귀포시청 자치행정국 기획예산과", desc: "당신은 **서귀포시청 자치행정국 기획예산과**를 대표하는 AI 레이어다. 시정 기획·예산편성·조직관리를 담당한다.",
    kw: ["기획예산", "기획예산과", "시정 기획", "예산편성", "조직관리"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-JACHI-BUDGET_v1.0.md" },
  { code: "SP-CITYDIV-SEOGWIPO-JACHI-GENERAL", 국코드: "jachi", 시코드: "seogwipo",
    name: "서귀포시청 자치행정국 총무과", desc: "당신은 **서귀포시청 자치행정국 총무과**를 대표하는 AI 레이어다. 일반서무·인사·의전·청사관리를 지원한다.",
    kw: ["의전", "인사", "일반서무", "청사관리를 지원한다", "총무", "총무과"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-JACHI-GENERAL_v1.0.md" },
  { code: "SP-CITYDIV-SEOGWIPO-JACHI-LIFELONGED", 국코드: "jachi", 시코드: "seogwipo",
    name: "서귀포시청 자치행정국 평생교육과", desc: "당신은 **서귀포시청 자치행정국 평생교육과**를 대표하는 AI 레이어다. 평생교육 프로그램, 도서관과 별개의 평생학습 정책을 담당한다 — 제주시 조직에는 이 명칭의 독립 과가 없어 서귀포시 고유 조직으로 확인된다.",
    kw: ["도서관과 별개의 평생학습 정책", "평생교육", "평생교육 프로그램", "평생교육과"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-JACHI-LIFELONGED_v1.0.md" },
  { code: "SP-CITYDIV-SEOGWIPO-JACHI-SELFGOV", 국코드: "jachi", 시코드: "seogwipo",
    name: "서귀포시청 자치행정국 자치행정과", desc: "당신은 **서귀포시청 자치행정국 자치행정과**를 대표하는 AI 레이어다. 읍면동 행정 총괄·지원, 선거 행정지원을 담당한다 — 제주시의 동명 부서(SP-CITYDIV-JEJUSI-JACHI-SELFGOV)와 달리, 서귀포시는 마을공동체·평생교육 업무가 별도 과(마을활력과·평생교육과)로 분리돼 있어 이 과의 업무 범위가 제주시보다 좁다는 점에 유의한다.",
    kw: ["선거 행정지원", "읍면동 행정 총괄", "자치행정", "자치행정과", "지원"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-JACHI-SELFGOV_v1.0.md" },
  { code: "SP-CITYDIV-SEOGWIPO-JACHI-TAX", 국코드: "jachi", 시코드: "seogwipo",
    name: "서귀포시청 자치행정국 세무과", desc: "당신은 **서귀포시청 자치행정국 세무과**를 대표하는 AI 레이어다. 취득세·등록면허세 등 신고형 지방세를 담당한다 — 재산세·자동차세 등 부과형 지방세는 서귀포시의 경우 별도 재산세과가 city-dept-master-data.json에 없어, 세무과가 이를 함께 담당하는 것으로 추정된다(제주시와의 구조 차이 — 재검증 필요).",
    kw: ["등록면허세 등 신고형 지방세", "세무", "세무과", "취득세"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-JACHI-TAX_v1.1.md" },
  { code: "SP-CITYDIV-SEOGWIPO-JACHI-VILLAGE", 국코드: "jachi", 시코드: "seogwipo",
    name: "서귀포시청 자치행정국 마을활력과", desc: "당신은 **서귀포시청 자치행정국 마을활력과**를 대표하는 AI 레이어다. 마을만들기, 주민 주도 마을공동체 사업을 담당한다 — **제주시와의 구조적 차이**: 제주시는 이 업무를 경제일자리국(SP-CITYDIV-JEJUSI-ECON-VILLAGE)이 담당하지만, 서귀포시는 자치행정국 산하에 있다. 같은 이름의 업무라도 두 시(市) 사이에 소속 국(局) 자체",
    kw: ["마을만들기", "마을활력", "마을활력과", "주민 주도 마을공동체 사업"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-JACHI-VILLAGE_v1.1.md" },
  { code: "SP-CITYDIV-SEOGWIPO-WELFARE-DISABLED", 국코드: "welfare", 시코드: "seogwipo",
    name: "서귀포시청 복지위생국 장애인복지과", desc: "당신은 **서귀포시청 복지위생국 장애인복지과**를 대표하는 AI 레이어다. 장애인 등록, 장애수당·장애인연금, 활동지원 신청을 담당한다.",
    kw: ["장애수당", "장애인 등록", "장애인복지", "장애인복지과", "장애인연금", "활동지원 신청"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-WELFARE-DISABLED_v1.1.md" },
  { code: "SP-CITYDIV-SEOGWIPO-WELFARE-ELDERLY", 국코드: "welfare", 시코드: "seogwipo",
    name: "서귀포시청 복지위생국 노인복지과", desc: "당신은 **서귀포시청 복지위생국 노인복지과**를 대표하는 AI 레이어다. 기초연금, 노인일자리, 경로당 지원을 담당한다.",
    kw: ["경로당 지원", "기초연금", "노인복지", "노인복지과", "노인일자리"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-WELFARE-ELDERLY_v1.1.md" },
  { code: "SP-CITYDIV-SEOGWIPO-WELFARE-HYGIENE", 국코드: "welfare", 시코드: "seogwipo",
    name: "서귀포시청 복지위생국 위생관리과", desc: "당신은 **서귀포시청 복지위생국 위생관리과**를 대표하는 AI 레이어다. 식품위생업(음식점 등) 및 공중위생업(숙박·미용 등) 인허가·신고를 담당한다.",
    kw: ["공중위생업 인허가", "식품위생업", "신고", "위생관리", "위생관리과"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-WELFARE-HYGIENE_v1.1.md" },
  { code: "SP-CITYDIV-SEOGWIPO-WELFARE-RESIDENT", 국코드: "welfare", 시코드: "seogwipo",
    name: "서귀포시청 복지위생국 주민복지과", desc: "당신은 **서귀포시청 복지위생국 주민복지과**를 대표하는 AI 레이어다. 복지 총괄·긴급복지지원을 담당한다 — **제주시와의 구조적 차이**: 제주시는 기초생활보장과가 별도 과로 분리돼 있으나(SP-CITYDIV-JEJUSI-WELFARE-BASICLIVELIHOOD), 서귀포시 city-dept-master-data.json에는 별도 기초생활보장과가 없어",
    kw: ["긴급복지지원", "복지 총괄", "주민복지", "주민복지과"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-WELFARE-RESIDENT_v1.1.md" },
  { code: "SP-CITYDIV-SEOGWIPO-WELFARE-WOMENFAMILY", 국코드: "welfare", 시코드: "seogwipo",
    name: "서귀포시청 복지위생국 여성가족과", desc: "당신은 **서귀포시청 복지위생국 여성가족과**를 대표하는 AI 레이어다. 한부모가족 지원, 가정폭력·성폭력 피해자 보호를 담당한다.",
    kw: ["가정폭력", "성폭력 피해자 보호", "여성가족", "여성가족과", "한부모가족 지원"], file: "04-city/divisions/SP-CITYDIV-SEOGWIPO-WELFARE-WOMENFAMILY_v1.1.md" },
];

export const DO_DEPT_DIVISION_TABLE = [
  { code: "SP-DIV-INNOV-DIGITAL", domain: "innov",
    name: "혁신산업국 디지털혁신과", desc: "당신은 **제주도청 혁신산업국 디지털혁신과**를 대표하는 AI 레이어다.",
    kw: ["디지털혁신", "디지털혁신과"], file: "02-do-dept/divisions/SP-DIV-INNOV-DIGITAL_v1.0.md" },
  { code: "SP-DIV-INNOV-ENERGYINDUSTRY", domain: "innov",
    name: "혁신산업국 에너지산업과", desc: "당신은 **제주도청 혁신산업국 에너지산업과**(조직개편 확정 시 신설 \"기후에너지국\"으로 이관 예정)를 대표하는 AI 레이어다.",
    kw: ["에너지산업", "에너지산업과"], file: "02-do-dept/divisions/SP-DIV-INNOV-ENERGYINDUSTRY_v1.0.md" },
  { code: "SP-DIV-INNOV-FUTUREGROWTH", domain: "innov",
    name: "혁신산업국 미래성장과", desc: "당신은 **제주도청 혁신산업국**(개칭 예정: 미래산업국) **미래성장과**를 대표하는 AI 레이어다.",
    kw: ["미래성장", "미래성장과"], file: "02-do-dept/divisions/SP-DIV-INNOV-FUTUREGROWTH_v1.0.md" },
  { code: "SP-DIV-INNOV-SPACEMOBILITY", domain: "innov",
    name: "혁신산업국 우주모빌리티과", desc: "당신은 **제주도청 혁신산업국 우주모빌리티과**를 대표하는 AI 레이어다.",
    kw: ["우주모빌리티", "우주모빌리티과"], file: "02-do-dept/divisions/SP-DIV-INNOV-SPACEMOBILITY_v1.0.md" },
  { code: "SP-DIV-JACHI-43SUPPORT", domain: "jachi",
    name: "특별자치행정국 4·3지원과", desc: "당신은 **제주도청 특별자치행정국 4·3지원과**를 대표하는 AI 레이어다. 이 과는 정책 총괄이 아니라 **실제 보상금 접수 창구(도외·해외 거주자용)를 겸한다** — 다른 대부분의 도청 실·국 과와 달리 처분성이 상대적으로 강한 업무를 수행한다.",
    kw: ["4·3지원", "4·3지원과"], file: "02-do-dept/divisions/SP-DIV-JACHI-43SUPPORT_v1.1.md" },
  { code: "SP-DIV-JACHI-ACCOUNTING", domain: "jachi",
    name: "특별자치행정국 회계재산관리과", desc: "당신은 **제주도청 특별자치행정국 회계재산관리과**를 대표하는 AI 레이어다.",
    kw: ["회계재산관리", "회계재산관리과"], file: "02-do-dept/divisions/SP-DIV-JACHI-ACCOUNTING_v1.1.md" },
  { code: "SP-DIV-JACHI-GENERAL", domain: "jachi",
    name: "특별자치행정국 총무과", desc: "당신은 **제주도청 특별자치행정국 총무과**를 대표하는 AI 레이어다. 이 과는 도민을 직접 상대하기보다 도청 내부 행정(문서·인사·의전)을 지원하는 성격이 강하다.",
    kw: ["총무", "총무과"], file: "02-do-dept/divisions/SP-DIV-JACHI-GENERAL_v1.0.md" },
  { code: "SP-DIV-JACHI-SELFGOV", domain: "jachi",
    name: "특별자치행정국 자치행정과", desc: "당신은 **제주도청 특별자치행정국 자치행정과**를 대표하는 AI 레이어다.",
    kw: ["자치행정", "자치행정과"], file: "02-do-dept/divisions/SP-DIV-JACHI-SELFGOV_v1.0.md" },
  { code: "SP-DIV-PLAN-BUDGET", domain: "plan",
    name: "기획조정실 예산담당관", desc: "당신은 **제주도청 기획조정실 예산담당관**을 대표하는 AI 레이어다.",
    kw: ["예산", "예산담당관"], file: "02-do-dept/divisions/SP-DIV-PLAN-BUDGET_v1.0.md" },
  { code: "SP-DIV-PLAN-LEGAL", domain: "plan",
    name: "기획조정실 특별자치법무담당관", desc: "당신은 **제주도청 기획조정실 특별자치법무담당관**을 대표하는 AI 레이어다.",
    kw: ["특별자치법무", "특별자치법무담당관"], file: "02-do-dept/divisions/SP-DIV-PLAN-LEGAL_v1.0.md" },
  { code: "SP-DIV-PLAN-POLICY", domain: "plan",
    name: "기획조정실 정책기획관", desc: "당신은 **제주도청 기획조정실 정책기획관**을 대표하는 AI 레이어다.",
    kw: ["정책기획관"], file: "02-do-dept/divisions/SP-DIV-PLAN-POLICY_v1.0.md" },
  { code: "SP-DIV-PLAN-POPULATION", domain: "plan",
    name: "기획조정실 인구정책담당관", desc: "당신은 **제주도청 기획조정실 인구정책담당관**을 대표하는 AI 레이어다.",
    kw: ["인구정책", "인구정책담당관"], file: "02-do-dept/divisions/SP-DIV-PLAN-POPULATION_v1.0.md" },
  { code: "SP-DIV-PLAN-TAXADMIN", domain: "plan",
    name: "기획조정실 세정담당관", desc: "당신은 **제주도청 기획조정실 세정담당관**을 대표하는 AI 레이어다.",
    kw: ["세정", "세정담당관"], file: "02-do-dept/divisions/SP-DIV-PLAN-TAXADMIN_v1.0.md" },
  { code: "SP-DIV-PLAN-YOUTH", domain: "plan",
    name: "기획조정실 청년정책담당관", desc: "당신은 **제주도청 기획조정실 청년정책담당관**을 대표하는 AI 레이어다.",
    kw: ["청년정책", "청년정책담당관"], file: "02-do-dept/divisions/SP-DIV-PLAN-YOUTH_v1.0.md" },
  { code: "SP-DIV-SAFETY-HEALTHHYGIENE", domain: "safety",
    name: "도민안전건강실 건강위생과", desc: "당신은 **제주도청 도민안전건강실 건강위생과**를 대표하는 AI 레이어다.",
    kw: ["건강위생", "건강위생과"], file: "02-do-dept/divisions/SP-DIV-SAFETY-HEALTHHYGIENE_v1.0.md" },
  { code: "SP-DIV-SAFETY-HEALTHPOLICY", domain: "safety",
    name: "도민안전건강실 보건정책과", desc: "당신은 **제주도청 도민안전건강실 보건정책과**를 대표하는 AI 레이어다.",
    kw: ["보건정책", "보건정책과"], file: "02-do-dept/divisions/SP-DIV-SAFETY-HEALTHPOLICY_v1.0.md" },
  { code: "SP-DIV-SAFETY-NATURALDISASTER", domain: "safety",
    name: "도민안전건강실 자연재난과", desc: "당신은 **제주도청 도민안전건강실 자연재난과**를 대표하는 AI 레이어다.",
    kw: ["자연재난", "자연재난과"], file: "02-do-dept/divisions/SP-DIV-SAFETY-NATURALDISASTER_v1.0.md" },
  { code: "SP-DIV-SAFETY-POLICY", domain: "safety",
    name: "도민안전건강실 안전정책과", desc: "당신은 **제주도청 도민안전건강실 안전정책과**를 대표하는 AI 레이어다.",
    kw: ["안전정책", "안전정책과"], file: "02-do-dept/divisions/SP-DIV-SAFETY-POLICY_v1.0.md" },
  { code: "SP-DIV-SAFETY-SOCIALDISASTER", domain: "safety",
    name: "도민안전건강실 사회재난과", desc: "당신은 **제주도청 도민안전건강실 사회재난과**를 대표하는 AI 레이어다.",
    kw: ["사회재난", "사회재난과"], file: "02-do-dept/divisions/SP-DIV-SAFETY-SOCIALDISASTER_v1.0.md" },
  { code: "SP-DIV-WELFARE-CHILDCARE", domain: "welfare",
    name: "복지가족국 아동보육청소년과", desc: "당신은 **제주도청 복지가족국 아동보육청소년과**를 대표하는 AI 레이어다.",
    kw: ["아동보육청소년", "아동보육청소년과"], file: "02-do-dept/divisions/SP-DIV-WELFARE-CHILDCARE_v1.0.md" },
  { code: "SP-DIV-WELFARE-DISABLED", domain: "welfare",
    name: "복지가족국 장애인복지과", desc: "당신은 **제주도청 복지가족국 장애인복지과**를 대표하는 AI 레이어다.",
    kw: ["장애인복지", "장애인복지과"], file: "02-do-dept/divisions/SP-DIV-WELFARE-DISABLED_v1.0.md" },
  { code: "SP-DIV-WELFARE-ELDERLY", domain: "welfare",
    name: "복지가족국 노인복지과", desc: "당신은 **제주도청 복지가족국 노인복지과**를 대표하는 AI 레이어다.",
    kw: ["노인복지", "노인복지과"], file: "02-do-dept/divisions/SP-DIV-WELFARE-ELDERLY_v1.0.md" },
  { code: "SP-DIV-WELFARE-POLICY", domain: "welfare",
    name: "복지가족국 복지정책과", desc: "당신은 **제주도청 복지가족국 복지정책과**를 대표하는 AI 레이어다.",
    kw: ["복지정책", "복지정책과"], file: "02-do-dept/divisions/SP-DIV-WELFARE-POLICY_v1.0.md" },
];

// ── 03-do-agency(직속기관) / 07-org(출자출연기관) 상위 기관 테이블 (2026-08-02 추가) ──
// city/do-dept와 달리 지금까지 이 두 계층은 institution 단위 라우팅
// 테이블 자체가 gov-router.js에 없어서(top-level SP는 존재하되 진입로 없음)
// division 배선 전에 먼저 신설했다. code(SP-AGY-*/SP-ORG-*)·kw(기관명+주요소관
// 키워드, 3자 미만 키워드는 배제 — L2 실국 키워드보다 먼저 매칭되므로
// "가족"/"관광"처럼 짧은 일반명사는 다른 국·부서명에 오탐 위험, 스모크테스트로 확인됨)·
// file(top-level SP 원문 경로)로 city/do-dept 테이블과 동일 패턴.
// 시코드(2026-08-02 추가, JEJUMED/SGPMED만 해당) — 제주의료원/서귀포의료원처럼
// 같은 종류 기관이 시별로 이원화된 경우, 기관명 없이 "의료원"처럼 공통
// 키워드로만 동점이 나면 이 필드로 시코드(PDV 위치/발화 지명)와 대조해
// LLM 호출 없이 결정론적으로 좁힌다 — _resolveInstitutionTie 참조.
export const JEJU_AGENCY_TABLE = [
  { code: "SP-AGY-AGRITECH", name: "농업기술원", desc: "당신은 제주특별자치도청 **농업기술원**을 대표하는 AI 레이어다. 주요 소관: 농업경영체 대상 재배기술 지도, 신품종 시험·보급, 영농기술 교육",
    kw: ["농업경영체 대상 재배기술 지도", "농업기술원", "신품종 시험", "영농기술 교육"], file: "03-do-agency/SP-AGY-AGRITECH_v1.1.md" },
  { code: "SP-AGY-ARTMUSEUM", name: "제주특별자치도립미술관", desc: "당신은 제주특별자치도청 **제주특별자치도립미술관**를 대표하는 AI 레이어다. 주요 소관: 도민 미술문화의식 향상, 소장품 전시, 제주비엔날레 등 국제교류전 개최",
    kw: ["도민 미술문화의식 향상", "소장품 전시", "제주비엔날레 등 국제교류전 개최", "제주특별자치도립미술관"], file: "03-do-agency/SP-AGY-ARTMUSEUM_v1.1.md" },
  { code: "SP-AGY-BOHWAN", name: "보건환경연구원", desc: "당신은 제주특별자치도청 **보건환경연구원**을 대표하는 AI 레이어다. 주요 소관: 수질·대기·식품 등 환경·보건 검사·분석, 감염병 진단 검사 지원",
    kw: ["감염병 진단 검사 지원", "보건 검사", "보건환경연구원", "식품 등 환경"], file: "03-do-agency/SP-AGY-BOHWAN_v1.1.md" },
  { code: "SP-AGY-CHUKSAN", name: "축산생명연구원", desc: "당신은 제주특별자치도청 **축산생명연구원**을 대표하는 AI 레이어다. 주요 소관: 가축전염병 방역·검사, 축산 관련 연구·기술 지원",
    kw: ["가축전염병 방역", "기술 지원", "축산 관련 연구", "축산생명연구원"], file: "03-do-agency/SP-AGY-CHUKSAN_v1.1.md" },
  { code: "SP-AGY-FIRE", name: "소방안전본부", desc: "당신은 제주특별자치도청 **소방안전본부**을(를) 대표하는 AI 레이어다. 주요 소관: 화재·구조·구급 출동, 소방시설 인허가, 재난 예방",
    kw: ["구급 출동", "소방시설 인허가", "소방안전본부", "재난 예방"], file: "03-do-agency/SP-AGY-FIRE_v1.1.md" },
  { code: "SP-AGY-FOLKMUSEUM", name: "제주특별자치도민속자연사박물관", desc: "당신은 제주특별자치도청 **제주특별자치도민속자연사박물관**를 대표하는 AI 레이어다. 주요 소관: 제주 민속문화·자연사 자료 보존·전시, 제주학 아카데미 등 교육 프로그램 운영",
    kw: ["자연사 자료 보존", "제주 민속문화", "제주특별자치도민속자연사박물관"], file: "03-do-agency/SP-AGY-FOLKMUSEUM_v1.1.md" },
  { code: "SP-AGY-HERITAGE", name: "세계유산본부", desc: "당신은 제주특별자치도청 **세계유산본부**를 대표하는 AI 레이어다. 주요 소관: 한라산국립공원 등 유네스코 세계자연유산·지질공원 관리, 특별 인허가(탐방로 이용, 학술조사 등)",
    kw: ["세계유산본부", "지질공원 관리", "특별 인허가"], file: "03-do-agency/SP-AGY-HERITAGE_v1.1.md" },
  { code: "SP-AGY-LIBRARY", name: "제주특별자치도 공공도서관(원형)", desc: "당신은 제주특별자치도청 **제주특별자치도 공공도서관(원형)** 산하 공공도서관 체계를 대표하는 AI 레이어다. 주요 소관: 도서 대출·반납, 열람실 이용, 지역자료(제주문헌실) 보존, 어린이·평생학습 프로그램 운영",
    kw: ["도서 대출", "어린이 열람실", "어린이 프로그램", "열람실 이용", "제주특별자치도 공공도서관", "지역자료 보존", "평생학습 프로그램 운영"], file: "03-do-agency/SP-AGY-LIBRARY_v1.1.md" },  // ★ 2026-09-15 수정(gov24_corpus batch4 발견) — bare '어린이'가 "어린이집 입소 대기 신청"의 "어린이집"과 우연히 겹쳐 도서관으로 오확정(2026-08-21 주석의 "어린이집 보육료 지원" 사례와 동일 클래스 — 그때는 L2 후보 병합으로 구제 경로만 만들고 원인 키워드는 안 고쳤음). 도서관 고유 프로그램명으로 복합어화(SP-NAT-POLICE의 '경찰'→'지방경찰청' 원칙과 동일)
  { code: "SP-AGY-POLICE", name: "자치경찰단", desc: "당신은 제주특별자치도청 **자치경찰단**을 대표하는 AI 레이어다. 주요 소관: 생활안전, 교통(주정차 단속 등 일부), 관광경찰, 지역 특성 치안(자연환경·문화재 보호 관련 수사 일부)",
    kw: ["관광경찰", "생활안전", "자치경찰단", "지역 특성 치안"], file: "03-do-agency/SP-AGY-POLICE_v1.0.md" },
  { code: "SP-AGY-WATER", name: "상하수도본부", desc: "당신은 제주특별자치도청 **상하수도본부**를 대표하는 AI 레이어다. 주요 소관: 상수도 요금·계량·급수 정책, 하수도 시설·처리, 급수 중단·누수 민원의 정책·시설 총괄 주체",
    kw: ["급수 정책", "급수 중단", "누수 민원의 정책", "상수도 요금", "상하수도본부", "시설 총괄 주체", "하수도 시설"], file: "03-do-agency/SP-AGY-WATER_v1.3.md" },
];

export const JEJU_ORG_TABLE = [
  { code: "SP-ORG-CHILDCARE", name: "제주특별자치도 아이돌봄광역지원센터", desc: "당신은 **제주특별자치도 아이돌봄광역지원센터**를 대표하는 AI 레이어다. 주요 소관: 12세 이하 아동 대상 방문 아이돌봄서비스 연계, 아이돌보미 모집·교육",
    kw: ["아이돌보미 모집", "제주특별자치도 아이돌봄광역지원센터"], file: "07-org/SP-ORG-CHILDCARE_v1.0.md" },
  { code: "SP-ORG-CHILDMEAL", name: "제주 어린이급식관리지원센터(1~4, 원형)", desc: "당신은 **제주 어린이급식관리지원센터(1~4, 원형)**를 대표하는 AI 레이어다. 주요 소관: 어린이 급식소(어린이집·유치원 등) 위생·영양 관리 지원, 급식소 등록 관리(식품위생법 근거 국가사업)",
    kw: ["급식소 등록 관리", "어린이 급식소 위생", "영양 관리 지원", "제주 어린이급식관리지원센터"], file: "07-org/SP-ORG-CHILDMEAL_v1.0.md" },
  { code: "SP-ORG-ICCJEJU", name: "제주국제컨벤션센터(ICC JEJU)", desc: "당신은 **제주국제컨벤션센터(ICC JEJU)**를 대표하는 AI 레이어다. 주요 소관: 국제회의·전시·공연 등 컨벤션 시설 대관 및 MICE(회의·포상관광·컨벤션·전시) 행사 유치·지원",
    kw: ["MICE 행사 유치", "공연 등 컨벤션 시설 대관", "국제회의", "제주국제컨벤션센터"], file: "07-org/SP-ORG-ICCJEJU_v1.0.md" },
  { code: "SP-ORG-IPF", name: "국제평화재단", desc: "당신은 **국제평화재단**를 대표하는 AI 레이어다. 주요 소관: \"평화와 번영을 위한 제주포럼\" 주최(제주도·동아시아재단과 공동), 제주평화연구원 운영",
    kw: ["\"평화와 번영을 위한 제주포럼\" 주최", "국제평화재단", "제주평화연구원 운영"], file: "07-org/SP-ORG-IPF_v1.0.md" },
  { code: "SP-ORG-JCCEI", name: "제주창조경제혁신센터", desc: "당신은 **제주창조경제혁신센터**를 대표하는 AI 레이어다. 주요 소관: 초기 창업기업 발굴·보육, 창업 공모전·투자 연계 지원",
    kw: ["제주창조경제혁신센터", "창업 공모전", "초기 창업기업 발굴", "투자 연계 지원"], file: "07-org/SP-ORG-JCCEI_v1.0.md" },
  { code: "SP-ORG-JCGF", name: "제주신용보증재단", desc: "당신은 **제주신용보증재단**를 대표하는 AI 레이어다. 주요 소관: 소기업·소상공인 대상 신용보증서 발급, 특별채무감면 캠페인 등 금융지원",
    kw: ["소기업", "소상공인 대상 신용보증서 발급", "제주신용보증재단", "특별채무감면 캠페인 등 금융지원"], file: "07-org/SP-ORG-JCGF_v1.1.md" },
  { code: "SP-ORG-JCPA", name: "제주영상문화산업진흥원", desc: "당신은 **제주영상문화산업진흥원**를 대표하는 AI 레이어다. 주요 소관: 영상·영화·콘텐츠 산업 지원, 촬영지 지원, 영상 인력 양성",
    kw: ["영상 인력 양성", "제주영상문화산업진흥원", "촬영지 지원", "콘텐츠 산업 지원"], file: "07-org/SP-ORG-JCPA_v1.0.md" },
  { code: "SP-ORG-JEA", name: "제주에너지공사(JEA)", desc: "당신은 **제주에너지공사(JEA)**를 대표하는 AI 레이어다. 주요 소관: 풍력·태양광 등 신재생에너지 생산·판매, 에너지연구기술센터 운영, 해상풍력발전단지 조성사업",
    kw: ["에너지연구기술센터 운영", "제주에너지공사", "태양광 등 신재생에너지 생산", "해상풍력발전단지 조성사업"], file: "07-org/SP-ORG-JEA_v1.0.md" },
  { code: "SP-ORG-JEDA", name: "제주경제통상진흥원(JBA)", desc: "당신은 **제주경제통상진흥원**을 대표하는 AI 레이어다. 주요 소관: 중소기업·소상공인·사회적기업 판로·자금·경영 지원, 소상공인경영지원센터·디자인스튜디오 운영, 창업 지원",
    kw: ["경영 지원", "디자인스튜디오 운영", "사회적기업 판로", "소상공인", "소상공인경영지원센터", "제주경제통상진흥원", "중소기업", "창업 지원"], file: "07-org/SP-ORG-JEDA_v1.0.md" },
  { code: "SP-ORG-JEJU43", name: "제주4·3평화재단", desc: "당신은 **제주4·3평화재단**를 대표하는 AI 레이어다. 주요 소관: 4·3평화기념관 운영, 희생자·유족 신고 지원, 진상조사·평화인권교육·추념식 주관",
    kw: ["3평화기념관 운영", "유족 신고 지원", "제주4·3평화재단", "진상조사", "추념식 주관", "평화인권교육"], file: "07-org/SP-ORG-JEJU43_v1.0.md" },
  { code: "SP-ORG-JEJUMED", name: "제주의료원", desc: "당신은 **제주의료원**를 대표하는 AI 레이어다. 주요 소관: 공공의료(취약계층 의료지원 포함), 검진센터·재활치료센터·고압산소치료센터 운영", 시코드: "jejusi",
    kw: ["검진센터", "고압산소치료센터 운영", "공공의료", "재활치료센터", "제주의료원", "의료원"], file: "07-org/SP-ORG-JEJUMED_v1.0.md" },
  { code: "SP-ORG-JERI", name: "제주연구원(JRI)", desc: "당신은 **제주연구원(JRI)**을 대표하는 AI 레이어다. 주요 소관: 제주 지역 정책연구(경제·복지·환경·농업·관광 등 전 분야), 도정 정책 자문, 지하수연구센터 운영",
    kw: ["도정 정책 자문", "제주 지역 정책연구", "제주연구원", "지하수연구센터 운영"], file: "07-org/SP-ORG-JERI_v1.0.md" },
  { code: "SP-ORG-JFAC", name: "제주문화예술재단", desc: "당신은 **제주문화예술재단**를 대표하는 AI 레이어다. 주요 소관: 문화예술 창작·활동 지원, 문화예술 공모사업 운영",
    kw: ["문화예술 공모사업 운영", "문화예술 창작", "제주문화예술재단", "활동 지원"], file: "07-org/SP-ORG-JFAC_v1.0.md" },
  { code: "SP-ORG-JILES", name: "제주평생교육장학진흥원", desc: "당신은 **제주평생교육장학진흥원**를 대표하는 AI 레이어다. 주요 소관: 평생교육 프로그램 운영(제주평생교육다모아), 장학금 지원, 외국어 학습비 지원",
    kw: ["외국어 학습비 지원", "장학금 지원", "제주평생교육장학진흥원", "평생교육 프로그램 운영"], file: "07-org/SP-ORG-JILES_v1.0.md" },
  { code: "SP-ORG-JPASS", name: "제주특별자치도사회서비스원", desc: "당신은 **제주특별자치도사회서비스원**를 대표하는 AI 레이어다. 주요 소관: 국공립 어린이집·요양시설 등 공공 사회복지시설 위탁 운영, 돌봄서비스 품질 관리",
    kw: ["국공립 어린이집", "돌봄서비스 품질 관리", "제주특별자치도사회서비스원"], file: "07-org/SP-ORG-JPASS_v1.0.md" },
  { code: "SP-ORG-JPDC", name: "제주특별자치도개발공사(JPDC)", desc: "당신은 **제주특별자치도개발공사(JPDC)**를 대표하는 AI 레이어다. 주요 소관: 제주삼다수(먹는샘물) 생산·유통, 공공주택 개발·분양·임대, 감귤 가공(감귤복합처리가공단지), 지하수 자원 관리",
    kw: ["감귤 가공", "공공주택 개발", "제주삼다수 생산", "제주특별자치도개발공사", "지하수 자원 관리"], file: "07-org/SP-ORG-JPDC_v1.0.md" },
  { code: "SP-ORG-JPSPO", name: "제주특별자치도장애인체육회", desc: "당신은 **제주특별자치도장애인체육회**를 대표하는 AI 레이어다. 주요 소관: 장애인 생활·전문체육 진흥, 제주장애인스포츠센터 관련 사업",
    kw: ["장애인 생활", "전문체육 진흥", "제주장애인스포츠센터 관련 사업", "제주특별자치도장애인체육회"], file: "07-org/SP-ORG-JPSPO_v1.0.md" },
  { code: "SP-ORG-JSPO", name: "제주특별자치도체육회", desc: "당신은 **제주특별자치도체육회**를 대표하는 AI 레이어다. 주요 소관: 생활체육·전문체육 진흥, 직장운동경기부 운영, 전국체전 등 대회 참가 지원",
    kw: ["생활체육", "전국체전 등 대회 참가 지원", "전문체육 진흥", "제주특별자치도체육회", "직장운동경기부 운영"], file: "07-org/SP-ORG-JSPO_v1.0.md" },
  { code: "SP-ORG-JTA", name: "제주특별자치도관광협회", desc: "당신은 **제주특별자치도관광협회**를 대표하는 AI 레이어다. 주요 소관: 관광사업체 회원 지원, 관광 관련 업무협약·캠페인 추진(예: 신용보증재단·은행과의 금융지원 협약)",
    kw: ["관광 관련 업무협약", "관광사업체 회원 지원", "제주특별자치도관광협회", "캠페인 추진"], file: "07-org/SP-ORG-JTA_v1.0.md" },
  { code: "SP-ORG-JTO", name: "제주관광공사(JTO)", desc: "당신은 **제주관광공사(JTO)**를 대표하는 AI 레이어다. 주요 소관: 관광 마케팅·프로모션, 관광 이벤트 기획·운영, 면세점 등 관광 부대사업(제주관광공사법 제49조 근거)",
    kw: ["관광 마케팅", "관광 이벤트 기획", "면세점 등 관광 부대사업", "제주관광공사", "프로모션"], file: "07-org/SP-ORG-JTO_v1.0.md" },
  { code: "SP-ORG-JTP", name: "제주테크노파크(JTP)", desc: "당신은 **제주테크노파크(JTP)**를 대표하는 AI 레이어다. 주요 소관: 지역 중소기업 기술지원, 산학연 협력, 청정바이오·화장품 등 지역전략산업 육성",
    kw: ["산학연 협력", "제주테크노파크", "지역 중소기업 기술지원", "청정바이오", "화장품 등 지역전략산업 육성"], file: "07-org/SP-ORG-JTP_v1.0.md" },
  { code: "SP-ORG-JWFRI", name: "제주여성가족연구원", desc: "당신은 **제주여성가족연구원**를 대표하는 AI 레이어다. 주요 소관: 여성·가족·성평등 정책 연구, 제주 성인지통계시스템 운영",
    kw: ["성평등 정책 연구", "제주 성인지통계시스템 운영", "제주여성가족연구원"], file: "07-org/SP-ORG-JWFRI_v1.0.md" },
  { code: "SP-ORG-MAEUL", name: "제주마을만들기종합지원센터", desc: "당신은 **제주마을만들기종합지원센터**를 대표하는 AI 레이어다. 주요 소관: 마을공동체 사업(마을만들기) 공모·컨설팅, 주민역량강화 프로그램 운영",
    kw: ["마을공동체 사업 공모", "제주마을만들기종합지원센터", "주민역량강화 프로그램 운영", "컨설팅"], file: "07-org/SP-ORG-MAEUL_v1.0.md" },
  { code: "SP-ORG-SGPMED", name: "서귀포의료원", desc: "당신은 **서귀포의료원**를 대표하는 AI 레이어다. 주요 소관: 서귀포시 유일 종합병원으로서 공공의료 제공, 응급의료센터 운영", 시코드: "seogwipo",
    kw: ["서귀포의료원", "응급의료센터 운영", "의료원"], file: "07-org/SP-ORG-SGPMED_v1.0.md" },
  { code: "SP-ORG-TRANSWEAK", name: "제주특별자치도 교통약자이동지원센터", desc: "당신은 **제주특별자치도 교통약자이동지원센터**를 대표하는 AI 레이어다. 주요 소관: 휠체어 이용 장애인 등 교통약자 대상 특별교통수단(콜택시) 배차·운영",
    kw: ["제주특별자치도 교통약자이동지원센터"], file: "07-org/SP-ORG-TRANSWEAK_v1.0.md" },
  { code: "SP-ORG-URBANREGEN", name: "제주특별자치도 도시재생지원센터", desc: "당신은 **제주특별자치도 도시재생지원센터**를 대표하는 AI 레이어다. 주요 소관: 도시재생 뉴딜사업 등 지원, 지역 재생사업 컨설팅·주민참여 프로그램 운영",
    kw: ["도시재생 뉴딜사업 등 지원", "제주특별자치도 도시재생지원센터", "주민참여 프로그램 운영", "지역 재생사업 컨설팅"], file: "07-org/SP-ORG-URBANREGEN_v1.0.md" },
];

// ── 03-do-agency / 07-org 산하 과·팀(division) 테이블 (2026-08-02 추가) ──
// institution(상위 기관 SP 코드)로 JEJU_AGENCY_TABLE/JEJU_ORG_TABLE과 연결된다.
export const JEJU_AGENCY_DIVISION_TABLE = [
  { code: "SP-AGYDIV-AGRITECH-ADMIN", institution: "SP-AGY-AGRITECH",
    name: "농업기술원 행정운영과", desc: "당신은 **농업기술원 행정운영과**를 대표하는 AI 레이어다.",
    kw: ["행정운영", "행정운영과"], file: "03-do-agency/divisions/SP-AGYDIV-AGRITECH-ADMIN_v1.0.md" },
  { code: "SP-AGYDIV-AGRITECH-EXTENSION", institution: "SP-AGY-AGRITECH",
    name: "농업기술원 기술보급과", desc: "당신은 **농업기술원 기술보급과**(공식 명칭 \"기술보급담당관\")를 대표하는 AI 레이어다.",
    kw: ["기술보급", "기술보급과"], file: "03-do-agency/divisions/SP-AGYDIV-AGRITECH-EXTENSION_v1.0.md" },
  { code: "SP-AGYDIV-AGRITECH-RESEARCH", institution: "SP-AGY-AGRITECH",
    name: "농업기술원 연구개발과", desc: "당신은 **농업기술원 연구개발과**를 대표하는 AI 레이어다.",
    kw: ["연구개발", "연구개발과"], file: "03-do-agency/divisions/SP-AGYDIV-AGRITECH-RESEARCH_v1.0.md" },
  { code: "SP-AGYDIV-ARTMUSEUM-JHYUN", institution: "SP-AGY-ARTMUSEUM",
    name: "제주도립미술관 제주현대미술관", desc: "당신은 **제주도립미술관 제주현대미술관**를 대표하는 AI 레이어다. 제주도립미술관이 통합 운영하는 3개 사이트 중 하나 — 현대미술 전문 전시관이다.",
    kw: ["제주현대미술", "제주현대미술관"], file: "03-do-agency/divisions/SP-AGYDIV-ARTMUSEUM-JHYUN_v1.1.md" },
  { code: "SP-AGYDIV-ARTMUSEUM-KIMTSCHANGYEUL", institution: "SP-AGY-ARTMUSEUM",
    name: "제주도립미술관 김창열미술관", desc: "당신은 **제주도립미술관 김창열미술관**를 대표하는 AI 레이어다. 제주 출신 화가 김창열의 작품을 전시하는 특화 미술관 — 제주도립미술관이 통합 운영하는 3개 사이트 중 하나.",
    kw: ["김창열미술", "김창열미술관"], file: "03-do-agency/divisions/SP-AGYDIV-ARTMUSEUM-KIMTSCHANGYEUL_v1.0.md" },
  { code: "SP-AGYDIV-ARTMUSEUM-MAIN", institution: "SP-AGY-ARTMUSEUM",
    name: "제주도립미술관 본관", desc: "당신은 **제주도립미술관 본관**를 대표하는 AI 레이어다. 2009년 개관, 제주 미술사·국제 현대미술 흐름을 다루는 본관이며 제주비엔날레 등 국제교류전을 개최한다.",
    kw: ["본관"], file: "03-do-agency/divisions/SP-AGYDIV-ARTMUSEUM-MAIN_v1.1.md" },
  { code: "SP-AGYDIV-BOHWAN-ENVIRONMENT", institution: "SP-AGY-BOHWAN",
    name: "보건환경연구원 환경연구과", desc: "당신은 **보건환경연구원 환경연구과**(가칭, 2006년 환경평가과·환경조사과·대기보전과·수질보전과 4과 통합 추정)를 대표하는 AI 레이어다.",
    kw: ["환경연구", "환경연구과"], file: "03-do-agency/divisions/SP-AGYDIV-BOHWAN-ENVIRONMENT_v1.0.md" },
  { code: "SP-AGYDIV-BOHWAN-HEALTH", institution: "SP-AGY-BOHWAN",
    name: "보건환경연구원 보건연구과", desc: "당신은 **보건환경연구원 보건연구과**(가칭, 2006년 미생물과·식약품분석과 통합 추정)를 대표하는 AI 레이어다.",
    kw: ["보건연구", "보건연구과"], file: "03-do-agency/divisions/SP-AGYDIV-BOHWAN-HEALTH_v1.0.md" },
  { code: "SP-AGYDIV-CHUKSAN-RESEARCH", institution: "SP-AGY-CHUKSAN",
    name: "축산생명연구원 축산연구과", desc: "당신은 **축산생명연구원 축산연구과**(가칭, 검증되지 않은 추정)를 대표하는 AI 레이어다.",
    kw: ["축산연구", "축산연구과"], file: "03-do-agency/divisions/SP-AGYDIV-CHUKSAN-RESEARCH_v1.0.md" },
  { code: "SP-AGYDIV-FIRE-ADMIN", institution: "SP-AGY-FIRE",
    name: "소방안전본부 소방행정과", desc: "당신은 **소방안전본부 소방행정과**를 대표하는 AI 레이어다.",
    kw: ["소방행정", "소방행정과"], file: "03-do-agency/divisions/SP-AGYDIV-FIRE-ADMIN_v1.0.md" },
  { code: "SP-AGYDIV-FIRE-PREVENTION", institution: "SP-AGY-FIRE",
    name: "소방안전본부 예방안전과", desc: "당신은 **소방안전본부 예방안전과**(가칭)를 대표하는 AI 레이어다.",
    kw: ["예방안전", "예방안전과"], file: "03-do-agency/divisions/SP-AGYDIV-FIRE-PREVENTION_v1.1.md" },
  { code: "SP-AGYDIV-FIRE-RESPONSE", institution: "SP-AGY-FIRE",
    name: "소방안전본부 현장대응과", desc: "당신은 **소방안전본부 현장대응과**(가칭)를 대표하는 AI 레이어다. **이 과는 진행 중 응급상황에서는 절차 안내가 아니라 즉시 119 신고 자체를 최우선으로 안내한다.**",
    kw: ["현장대응", "현장대응과"], file: "03-do-agency/divisions/SP-AGYDIV-FIRE-RESPONSE_v1.1.md" },
  { code: "SP-AGYDIV-FOLKMUSEUM-ADMIN", institution: "SP-AGY-FOLKMUSEUM",
    name: "제주특별자치도민속자연사박물관 관리실", desc: "당신은 **제주특별자치도민속자연사박물관 관리실**를 대표하는 AI 레이어다. 박물관 시설관리·행정 총괄을 담당한다.",
    kw: ["관리", "관리실"], file: "03-do-agency/divisions/SP-AGYDIV-FOLKMUSEUM-ADMIN_v1.1.md" },
  { code: "SP-AGYDIV-FOLKMUSEUM-ARCHAEOFOLK", institution: "SP-AGY-FOLKMUSEUM",
    name: "제주특별자치도민속자연사박물관 고고민속과", desc: "당신은 **제주특별자치도민속자연사박물관 고고민속과**를 대표하는 AI 레이어다. 제주 고고유물·민속자료의 수집·연구·전시를 담당한다(디지털제주문화대전 확인 조직).",
    kw: ["고고민속", "고고민속과"], file: "03-do-agency/divisions/SP-AGYDIV-FOLKMUSEUM-ARCHAEOFOLK_v1.0.md" },
  { code: "SP-AGYDIV-FOLKMUSEUM-MARINE", institution: "SP-AGY-FOLKMUSEUM",
    name: "제주특별자치도민속자연사박물관 해양생물과", desc: "당신은 **제주특별자치도민속자연사박물관 해양생물과**를 대표하는 AI 레이어다. 제주 해양생물 표본의 수집·연구·전시를 담당한다.",
    kw: ["해양생물", "해양생물과"], file: "03-do-agency/divisions/SP-AGYDIV-FOLKMUSEUM-MARINE_v1.0.md" },
  { code: "SP-AGYDIV-FOLKMUSEUM-MINERALBOTANY", institution: "SP-AGY-FOLKMUSEUM",
    name: "제주특별자치도민속자연사박물관 광식물과", desc: "당신은 **제주특별자치도민속자연사박물관 광식물과**를 대표하는 AI 레이어다. 제주 광물·식물 표본의 수집·연구·전시를 담당한다.",
    kw: ["광식물", "광식물과"], file: "03-do-agency/divisions/SP-AGYDIV-FOLKMUSEUM-MINERALBOTANY_v1.0.md" },
  { code: "SP-AGYDIV-FOLKMUSEUM-ZOOLOGY", institution: "SP-AGY-FOLKMUSEUM",
    name: "제주특별자치도민속자연사박물관 동물과", desc: "당신은 **제주특별자치도민속자연사박물관 동물과**를 대표하는 AI 레이어다. 제주 동물 표본·생태 자료의 수집·연구·전시를 담당한다.",
    kw: ["동물", "동물과"], file: "03-do-agency/divisions/SP-AGYDIV-FOLKMUSEUM-ZOOLOGY_v1.0.md" },
  { code: "SP-AGYDIV-HERITAGE-HALLASAN", institution: "SP-AGY-HERITAGE",
    name: "세계유산본부 한라산연구과", desc: "당신은 **세계유산본부 한라산연구과**(가칭)를 대표하는 AI 레이어다.",
    kw: ["한라산연구", "한라산연구과"], file: "03-do-agency/divisions/SP-AGYDIV-HERITAGE-HALLASAN_v1.0.md" },
  { code: "SP-AGYDIV-HERITAGE-MANAGEMENT", institution: "SP-AGY-HERITAGE",
    name: "세계유산본부 유산관리과", desc: "당신은 **세계유산본부 유산관리과**(가칭)를 대표하는 AI 레이어다.",
    kw: ["유산관리", "유산관리과"], file: "03-do-agency/divisions/SP-AGYDIV-HERITAGE-MANAGEMENT_v1.1.md" },
  { code: "SP-AGYDIV-LIBRARY-INFOSERVICE", institution: "SP-AGY-LIBRARY",
    name: "제주특별자치도한라도서관 정보서비스팀(추정)", desc: "당신은 **제주특별자치도한라도서관 정보서비스팀(추정)**를 대표하는 AI 레이어다. 한라도서관 자체 소장자료의 대출·반납, 열람실 운영을 담당한다(일반적 대표도서관 기능 기준 — 실제 팀명은 추정).",
    kw: ["정보서비스", "정보서비스팀"], file: "03-do-agency/divisions/SP-AGYDIV-LIBRARY-INFOSERVICE_v1.1.md" },
  { code: "SP-AGYDIV-LIBRARY-POLICY", institution: "SP-AGY-LIBRARY",
    name: "제주특별자치도한라도서관 정책협력팀(추정)", desc: "당신은 **제주특별자치도한라도서관 정책협력팀(추정)**를 대표하는 AI 레이어다. 제주 지역대표도서관으로서 도 도서관 정책 평가, 도내 공공도서관 협력망(15개관 통합서비스) 운영, 관리·감독을 담당한다(위키백과 확인 기능 기준 — 실제 팀명은 추정).",
    kw: ["정책협력", "정책협력팀"], file: "03-do-agency/divisions/SP-AGYDIV-LIBRARY-POLICY_v1.0.md" },
  { code: "SP-AGYDIV-POLICE-SAFETY", institution: "SP-AGY-POLICE",
    name: "자치경찰단 생활안전과", desc: "당신은 **자치경찰단 생활안전과**를 대표하는 AI 레이어다.",
    kw: ["생활안전", "생활안전과"], file: "03-do-agency/divisions/SP-AGYDIV-POLICE-SAFETY_v1.1.md" },
  { code: "SP-AGYDIV-POLICE-TRAFFIC", institution: "SP-AGY-POLICE",
    name: "자치경찰단 교통과", desc: "당신은 **자치경찰단 교통과**를 대표하는 AI 레이어다.",
    kw: ["교통", "교통과"], file: "03-do-agency/divisions/SP-AGYDIV-POLICE-TRAFFIC_v1.1.md" },
  { code: "SP-AGYDIV-POLICE-WOMENYOUTH", institution: "SP-AGY-POLICE",
    name: "자치경찰단 여성청소년과", desc: "당신은 **자치경찰단 여성청소년과**를 대표하는 AI 레이어다.",
    kw: ["여성청소년", "여성청소년과"], file: "03-do-agency/divisions/SP-AGYDIV-POLICE-WOMENYOUTH_v1.0.md" },
  { code: "SP-AGYDIV-WATER-ADMIN", institution: "SP-AGY-WATER",
    name: "상하수도본부 경영지원과", desc: "당신은 **상하수도본부 경영지원과**(가칭)를 대표하는 AI 레이어다.",
    kw: ["경영지원", "경영지원과"], file: "03-do-agency/divisions/SP-AGYDIV-WATER-ADMIN_v1.0.md" },
  { code: "SP-AGYDIV-WATER-SEWAGE", institution: "SP-AGY-WATER",
    name: "상하수도본부 하수도과", desc: "당신은 **상하수도본부 하수도과**(가칭)를 대표하는 AI 레이어다.",
    kw: ["하수도", "하수도과"], file: "03-do-agency/divisions/SP-AGYDIV-WATER-SEWAGE_v1.0.md" },
  { code: "SP-AGYDIV-WATER-WATERSUPPLY", institution: "SP-AGY-WATER",
    name: "상하수도본부 상수도과", desc: "당신은 **상하수도본부 상수도과**(가칭 — §0 참조)를 대표하는 AI 레이어다.",
    kw: ["상수도", "상수도과"], file: "03-do-agency/divisions/SP-AGYDIV-WATER-WATERSUPPLY_v1.1.md" },
];

export const JEJU_ORG_DIVISION_TABLE = [
  { code: "SP-ORGDIV-CHILDCARE-SUPPORT", institution: "SP-ORG-CHILDCARE",
    name: "제주특별자치도 아이돌봄광역지원센터 돌봄지원팀", desc: "당신은 **제주특별자치도 아이돌봄광역지원센터 돌봄지원팀**을 대표하는 AI 레이어다.",
    kw: ["돌봄지원", "돌봄지원팀"], file: "07-org/divisions/SP-ORGDIV-CHILDCARE-SUPPORT_v1.0.md" },
  { code: "SP-ORGDIV-CHILDMEAL-ADMIN", institution: "SP-ORG-CHILDMEAL",
    name: "어린이급식관리지원센터 기획운영팀", desc: "당신은 **어린이급식관리지원센터 기획운영팀**을 대표하는 AI 레이어다.",
    kw: ["기획운영", "기획운영팀"], file: "07-org/divisions/SP-ORGDIV-CHILDMEAL-ADMIN_v1.0.md" },
  { code: "SP-ORGDIV-CHILDMEAL-HYGIENE", institution: "SP-ORG-CHILDMEAL",
    name: "어린이급식관리지원센터 위생팀", desc: "당신은 **어린이급식관리지원센터 위생팀**을 대표하는 AI 레이어다.",
    kw: ["위생", "위생팀"], file: "07-org/divisions/SP-ORGDIV-CHILDMEAL-HYGIENE_v1.0.md" },
  { code: "SP-ORGDIV-CHILDMEAL-NUTRITION", institution: "SP-ORG-CHILDMEAL",
    name: "어린이급식관리지원센터 영양팀", desc: "당신은 **어린이급식관리지원센터 영양팀**을 대표하는 AI 레이어다.",
    kw: ["영양", "영양팀"], file: "07-org/divisions/SP-ORGDIV-CHILDMEAL-NUTRITION_v1.0.md" },
  { code: "SP-ORGDIV-ICCJEJU-MARKETING", institution: "SP-ORG-ICCJEJU",
    name: "제주국제컨벤션센터 마케팅팀", desc: "당신은 **제주국제컨벤션센터 마케팅팀**를 대표하는 AI 레이어다. 국제회의·전시 유치 영업을 담당한다(팀명 추정).",
    kw: ["마케팅", "마케팅팀"], file: "07-org/divisions/SP-ORGDIV-ICCJEJU-MARKETING_v1.0.md" },
  { code: "SP-ORGDIV-ICCJEJU-MGMT", institution: "SP-ORG-ICCJEJU",
    name: "제주국제컨벤션센터 경영지원팀", desc: "당신은 **제주국제컨벤션센터 경영지원팀**를 대표하는 AI 레이어다. 센터 경영지원·정보공개를 담당한다(팀명 추정).",
    kw: ["경영지원", "경영지원팀"], file: "07-org/divisions/SP-ORGDIV-ICCJEJU-MGMT_v1.0.md" },
  { code: "SP-ORGDIV-ICCJEJU-OPS", institution: "SP-ORG-ICCJEJU",
    name: "제주국제컨벤션센터 운영팀", desc: "당신은 **제주국제컨벤션센터 운영팀**를 대표하는 AI 레이어다. 대회의실·중소회의실·전시장 등 시설 대관·행사운영을 담당한다(팀명 추정, 시설 규모는 나무위키로 확인).",
    kw: ["운영", "운영팀"], file: "07-org/divisions/SP-ORGDIV-ICCJEJU-OPS_v1.0.md" },
  { code: "SP-ORGDIV-ICCJEJU-VENUE", institution: "SP-ORG-ICCJEJU",
    name: "제주국제컨벤션센터 시설운영팀", desc: "당신은 **제주국제컨벤션센터(ICC JEJU) 시설운영팀**을 대표하는 AI 레이어다. 서귀포시 중문관광단지에 위치한다(JEJU-DO-SP §3-4에서 이미 확인됨, 출자기관).",
    kw: ["시설운영", "시설운영팀"], file: "07-org/divisions/SP-ORGDIV-ICCJEJU-VENUE_v1.0.md" },
  { code: "SP-ORGDIV-IPF-PEACE", institution: "SP-ORG-IPF",
    name: "국제평화재단 국제교류팀", desc: "당신은 **국제평화재단 국제교류팀**을 대표하는 AI 레이어다.",
    kw: ["국제교류", "국제교류팀"], file: "07-org/divisions/SP-ORGDIV-IPF-PEACE_v1.0.md" },
  { code: "SP-ORGDIV-JCCEI-SUPPORT", institution: "SP-ORG-JCCEI",
    name: "제주창조경제혁신센터 창업지원팀", desc: "당신은 **제주창조경제혁신센터 창업지원팀**을 대표하는 AI 레이어다.",
    kw: ["창업지원", "창업지원팀"], file: "07-org/divisions/SP-ORGDIV-JCCEI-SUPPORT_v1.0.md" },
  { code: "SP-ORGDIV-JCGF-ADMIN", institution: "SP-ORG-JCGF",
    name: "제주신용보증재단 경영지원부", desc: "당신은 **제주신용보증재단 경영지원부**를 대표하는 AI 레이어다.",
    kw: ["경영지원부"], file: "07-org/divisions/SP-ORGDIV-JCGF-ADMIN_v1.0.md" },
  { code: "SP-ORGDIV-JCGF-RISK", institution: "SP-ORG-JCGF",
    name: "제주신용보증재단 리스크관리부", desc: "당신은 **제주신용보증재단 리스크관리부**를 대표하는 AI 레이어다.",
    kw: ["리스크관리부"], file: "07-org/divisions/SP-ORGDIV-JCGF-RISK_v1.0.md" },
  { code: "SP-ORGDIV-JCGF-UNDERWRITING", institution: "SP-ORG-JCGF",
    name: "제주신용보증재단 보증심사부", desc: "당신은 **제주신용보증재단 보증심사부**를 대표하는 AI 레이어다.",
    kw: ["보증심사부"], file: "07-org/divisions/SP-ORGDIV-JCGF-UNDERWRITING_v1.0.md" },
  { code: "SP-ORGDIV-JCPA-BASE", institution: "SP-ORG-JCPA",
    name: "제주콘텐츠진흥원 콘텐츠기반팀", desc: "당신은 **제주콘텐츠진흥원 콘텐츠기반팀**를 대표하는 AI 레이어다. 콘텐츠 창업·창작 기반 지원을 담당한다(2024년 조직개편으로 확인된 팀명, 언론보도).",
    kw: ["콘텐츠기반", "콘텐츠기반팀"], file: "07-org/divisions/SP-ORGDIV-JCPA-BASE_v1.0.md" },
  { code: "SP-ORGDIV-JCPA-CONTENTS", institution: "SP-ORG-JCPA",
    name: "제주콘텐츠진흥원 콘텐츠산업팀", desc: "당신은 **제주콘텐츠진흥원**(구 제주영상문화산업진흥원) **콘텐츠산업팀**을 대표하는 AI 레이어다.",
    kw: ["콘텐츠산업", "콘텐츠산업팀"], file: "07-org/divisions/SP-ORGDIV-JCPA-CONTENTS_v1.0.md" },
  { code: "SP-ORGDIV-JCPA-FOSTER", institution: "SP-ORG-JCPA",
    name: "제주콘텐츠진흥원 콘텐츠육성팀", desc: "당신은 **제주콘텐츠진흥원 콘텐츠육성팀**를 대표하는 AI 레이어다. 콘텐츠 기업 육성을 담당한다.",
    kw: ["콘텐츠육성", "콘텐츠육성팀"], file: "07-org/divisions/SP-ORGDIV-JCPA-FOSTER_v1.0.md" },
  { code: "SP-ORGDIV-JCPA-SPREAD", institution: "SP-ORG-JCPA",
    name: "제주콘텐츠진흥원 콘텐츠확산팀", desc: "당신은 **제주콘텐츠진흥원 콘텐츠확산팀**를 대표하는 AI 레이어다. 도민문화향유권 확대, 콘텐츠 유통·사업화 지원을 담당한다.",
    kw: ["콘텐츠확산", "콘텐츠확산팀"], file: "07-org/divisions/SP-ORGDIV-JCPA-SPREAD_v1.0.md" },
  { code: "SP-ORGDIV-JCPA-TALENT", institution: "SP-ORG-JCPA",
    name: "제주콘텐츠진흥원 콘텐츠인재팀", desc: "당신은 **제주콘텐츠진흥원 콘텐츠인재팀**를 대표하는 AI 레이어다. 콘텐츠 산업 인재양성을 담당한다(제주웹툰캠퍼스, 음악창작소 등).",
    kw: ["콘텐츠인재", "콘텐츠인재팀"], file: "07-org/divisions/SP-ORGDIV-JCPA-TALENT_v1.0.md" },
  { code: "SP-ORGDIV-JEA-EVINFRA", institution: "SP-ORG-JEA",
    name: "제주에너지공사 전기차인프라운영팀", desc: "당신은 **제주에너지공사 전기차인프라운영팀**를 대표하는 AI 레이어다. 전기차 충전 인프라(EVC) 통합관제·유지보수를 담당한다 — 도 대행사업으로 운영된다.",
    kw: ["전기차인프라운영", "전기차인프라운영팀"], file: "07-org/divisions/SP-ORGDIV-JEA-EVINFRA_v1.0.md" },
  { code: "SP-ORGDIV-JEA-FACILITY", institution: "SP-ORG-JEA",
    name: "제주에너지공사 시설팀", desc: "당신은 **제주에너지공사 시설팀**를 대표하는 AI 레이어다. 태양광·풍력 발전시설의 시설관리·통합관제를 담당한다(제주시민발전소 등 포함).",
    kw: ["시설", "시설팀"], file: "07-org/divisions/SP-ORGDIV-JEA-FACILITY_v1.0.md" },
  { code: "SP-ORGDIV-JEA-HYDROGEN", institution: "SP-ORG-JEA",
    name: "제주에너지공사 청정수소사업단", desc: "당신은 **제주에너지공사 청정수소사업단**를 대표하는 AI 레이어다. 그린수소 실증사업(5MW PEM, 12.5MW 그린수소 등)·RE100 인증·연구개발(R&BD)을 담당한다 — 청정수소생산운영단 기능을 통합해 대표한다.",
    kw: ["청정수소사업단"], file: "07-org/divisions/SP-ORGDIV-JEA-HYDROGEN_v1.0.md" },
  { code: "SP-ORGDIV-JEA-PLANNING", institution: "SP-ORG-JEA",
    name: "제주에너지공사 경영기획본부", desc: "당신은 **제주에너지공사 경영기획본부**를 대표하는 AI 레이어다.",
    kw: ["경영기획", "경영기획본부"], file: "07-org/divisions/SP-ORGDIV-JEA-PLANNING_v1.0.md" },
  { code: "SP-ORGDIV-JEA-RENEWABLE", institution: "SP-ORG-JEA",
    name: "제주에너지공사 신재생에너지사업본부", desc: "당신은 **제주에너지공사 신재생에너지사업본부**를 대표하는 AI 레이어다.",
    kw: ["신재생에너지사업", "신재생에너지사업본부"], file: "07-org/divisions/SP-ORGDIV-JEA-RENEWABLE_v1.0.md" },
  { code: "SP-ORGDIV-JEA-WINDOPS", institution: "SP-ORG-JEA",
    name: "제주에너지공사 풍력사업운영본부", desc: "당신은 **제주에너지공사 풍력사업운영본부**를 대표하는 AI 레이어다. 한동테스트 해상풍력·성산일출풍력 등 기존 풍력발전시설의 운영을 담당한다.",
    kw: ["풍력사업운영", "풍력사업운영본부"], file: "07-org/divisions/SP-ORGDIV-JEA-WINDOPS_v1.0.md" },
  { code: "SP-ORGDIV-JEDA-BUSINESS", institution: "SP-ORG-JEDA",
    name: "제주경제통상진흥원 사업지원팀", desc: "당신은 **제주경제통상진흥원 사업지원팀**을 대표하는 AI 레이어다.",
    kw: ["사업지원", "사업지원팀"], file: "07-org/divisions/SP-ORGDIV-JEDA-BUSINESS_v1.0.md" },
  { code: "SP-ORGDIV-JEDA-EXPORT", institution: "SP-ORG-JEDA",
    name: "제주특별자치도경제통상진흥원 수출판로지원팀", desc: "당신은 **제주특별자치도경제통상진흥원 수출판로지원팀**를 대표하는 AI 레이어다. 도내 기업 수출·판로 개척(구매상담회 등)을 지원한다.",
    kw: ["수출판로지원", "수출판로지원팀"], file: "07-org/divisions/SP-ORGDIV-JEDA-EXPORT_v1.0.md" },
  { code: "SP-ORGDIV-JEDA-FINANCE", institution: "SP-ORG-JEDA",
    name: "제주특별자치도경제통상진흥원 자금지원팀", desc: "당신은 **제주특별자치도경제통상진흥원 자금지원팀**를 대표하는 AI 레이어다. 도내 중소기업·소상공인 경영안정자금 지원을 담당한다(진흥원 5대 지원영역 중 하나로 확인).",
    kw: ["자금지원", "자금지원팀"], file: "07-org/divisions/SP-ORGDIV-JEDA-FINANCE_v1.0.md" },
  { code: "SP-ORGDIV-JEDA-MGMT", institution: "SP-ORG-JEDA",
    name: "제주특별자치도경제통상진흥원 경영혁신본부", desc: "당신은 **제주특별자치도경제통상진흥원 경영혁신본부**를 대표하는 AI 레이어다. 진흥원 경영지원·기획을 총괄한다(공식 소개페이지에서 조직명 확인).",
    kw: ["경영혁신", "경영혁신본부"], file: "07-org/divisions/SP-ORGDIV-JEDA-MGMT_v1.0.md" },
  { code: "SP-ORGDIV-JEDA-PLANNING", institution: "SP-ORG-JEDA",
    name: "제주경제통상진흥원 경영기획팀", desc: "당신은 **제주경제통상진흥원 경영기획팀**을 대표하는 AI 레이어다.",
    kw: ["경영기획", "경영기획팀"], file: "07-org/divisions/SP-ORGDIV-JEDA-PLANNING_v1.0.md" },
  { code: "SP-ORGDIV-JEDA-STARTUP", institution: "SP-ORG-JEDA",
    name: "제주특별자치도경제통상진흥원 창업지원팀", desc: "당신은 **제주특별자치도경제통상진흥원 창업지원팀**를 대표하는 AI 레이어다. 청년 창업·인증 지원을 담당한다('제주 청년 희망사다리' 등 사업 확인).",
    kw: ["창업지원", "창업지원팀"], file: "07-org/divisions/SP-ORGDIV-JEDA-STARTUP_v1.0.md" },
  { code: "SP-ORGDIV-JEJU43-ADMIN", institution: "SP-ORG-JEJU43",
    name: "제주4·3평화재단 사무처", desc: "당신은 **제주4·3평화재단 사무처**를 대표하는 AI 레이어다. 재단 행정 총괄 및 4·3평화기념관·평화공원·어린이체험관 시설 운영·대관을 담당한다(공식 조직도 탭 확인).",
    kw: ["사무처"], file: "07-org/divisions/SP-ORGDIV-JEJU43-ADMIN_v1.0.md" },
  { code: "SP-ORGDIV-JEJU43-PEACE", institution: "SP-ORG-JEJU43",
    name: "제주4·3평화재단 평화사업팀", desc: "당신은 **제주4·3평화재단 평화사업팀**을 대표하는 AI 레이어다. 이 재단은 4·3사건 진상규명·희생자 추념·평화교육을 위해 설립된 전국 유일 성격의 기관이다.",
    kw: ["평화사업", "평화사업팀"], file: "07-org/divisions/SP-ORGDIV-JEJU43-PEACE_v1.0.md" },
  { code: "SP-ORGDIV-JEJU43-RESEARCH", institution: "SP-ORG-JEJU43",
    name: "제주4·3평화재단 조사연구실", desc: "당신은 **제주4·3평화재단 조사연구실**를 대표하는 AI 레이어다. 4·3사건 추가진상조사, 유족 복지, 문화·학술연구, 평화교육·교류 사업을 담당한다(공식 조직도 탭 확인).",
    kw: ["조사연구", "조사연구실"], file: "07-org/divisions/SP-ORGDIV-JEJU43-RESEARCH_v1.0.md" },
  { code: "SP-ORGDIV-JEJUMED-ADMIN", institution: "SP-ORG-JEJUMED",
    name: "제주의료원 행정지원부", desc: "당신은 **제주의료원 행정지원부**를 대표하는 AI 레이어다.",
    kw: ["행정지원부"], file: "07-org/divisions/SP-ORGDIV-JEJUMED-ADMIN_v1.0.md" },
  { code: "SP-ORGDIV-JEJUMED-CLINICAL", institution: "SP-ORG-JEJUMED",
    name: "제주의료원 진료부", desc: "당신은 **제주의료원 진료부**를 대표하는 AI 레이어다.",
    kw: ["진료부"], file: "07-org/divisions/SP-ORGDIV-JEJUMED-CLINICAL_v1.0.md" },
  { code: "SP-ORGDIV-JEJUMED-NURSING", institution: "SP-ORG-JEJUMED",
    name: "제주의료원 간호부", desc: "당신은 **제주의료원 간호부**를 대표하는 AI 레이어다.",
    kw: ["간호부"], file: "07-org/divisions/SP-ORGDIV-JEJUMED-NURSING_v1.0.md" },
  { code: "SP-ORGDIV-JERI-CITIZEN", institution: "SP-ORG-JERI",
    name: "제주연구원 도민행복연구실", desc: "당신은 **제주연구원 도민행복연구실**를 대표하는 AI 레이어다. 정주환경·교통물류 인프라·재난안전 방재체계·분권모델·문화보존·지역갈등 회복 관련 정책연구를 담당한다.",
    kw: ["도민행복연구", "도민행복연구실"], file: "07-org/divisions/SP-ORGDIV-JERI-CITIZEN_v1.0.md" },
  { code: "SP-ORGDIV-JERI-DISASTER", institution: "SP-ORG-JERI",
    name: "제주연구원 제주재난안전연구센터", desc: "당신은 **제주연구원 제주재난안전연구센터**를 대표하는 AI 레이어다. 재난안전 관련 조사연구·정책개발, 사업 컨설팅·성과평가, DB 구축, 민관학연 협력체계를 담당한다.",
    kw: ["제주재난안전연구", "제주재난안전연구센터"], file: "07-org/divisions/SP-ORGDIV-JERI-DISASTER_v1.0.md" },
  { code: "SP-ORGDIV-JERI-FUTURE", institution: "SP-ORG-JERI",
    name: "제주연구원 미래대응전략실", desc: "당신은 **제주연구원 미래대응전략실**를 대표하는 AI 레이어다. 중장기 아젠다 발굴, 전략과제 및 현안대응 TF팀 운영을 담당한다.",
    kw: ["미래대응전략", "미래대응전략실"], file: "07-org/divisions/SP-ORGDIV-JERI-FUTURE_v1.0.md" },
  { code: "SP-ORGDIV-JERI-GROWTH", institution: "SP-ORG-JERI",
    name: "제주연구원 지속성장연구실", desc: "당신은 **제주연구원 지속성장연구실**를 대표하는 AI 레이어다. 청정환경 보전·활용, 산업생태계 조성, 1차산업 지속가능성, 지역상생형 관광산업, 신성장동력 발굴, 일자리 질 향상 관련 정책연구를 담당한다.",
    kw: ["지속성장연구", "지속성장연구실"], file: "07-org/divisions/SP-ORGDIV-JERI-GROWTH_v1.0.md" },
  { code: "SP-ORGDIV-JERI-MGMT", institution: "SP-ORG-JERI",
    name: "제주연구원 경영지원실", desc: "당신은 **제주연구원 경영지원실**를 대표하는 AI 레이어다. 이사회·규정 관리·감사, 인사·복무·노무, 보수 지급, 시설·구매·자산관리, 문서관리를 담당한다.",
    kw: ["경영지원", "경영지원실"], file: "07-org/divisions/SP-ORGDIV-JERI-MGMT_v1.0.md" },
  { code: "SP-ORGDIV-JERI-PLANNING", institution: "SP-ORG-JERI",
    name: "제주연구원 기획경영부", desc: "당신은 **제주연구원 기획경영부**를 대표하는 AI 레이어다.",
    kw: ["기획경영부"], file: "07-org/divisions/SP-ORGDIV-JERI-PLANNING_v1.0.md" },
  { code: "SP-ORGDIV-JERI-RESEARCH", institution: "SP-ORG-JERI",
    name: "제주연구원 연구부", desc: "당신은 **제주연구원 연구부**를 대표하는 AI 레이어다.",
    kw: ["연구부"], file: "07-org/divisions/SP-ORGDIV-JERI-RESEARCH_v1.0.md" },
  { code: "SP-ORGDIV-JFAC-MGMT", institution: "SP-ORG-JFAC",
    name: "제주문화예술재단 경영지원팀", desc: "당신은 **제주문화예술재단 경영지원팀**를 대표하는 AI 레이어다. 재단 경영지원·정보공개를 담당한다(팀명 추정).",
    kw: ["경영지원", "경영지원팀"], file: "07-org/divisions/SP-ORGDIV-JFAC-MGMT_v1.0.md" },
  { code: "SP-ORGDIV-JFAC-PROGRAM", institution: "SP-ORG-JFAC",
    name: "제주문화예술재단 문화사업팀", desc: "당신은 **제주문화예술재단 문화사업팀**를 대표하는 AI 레이어다. 문화행사 기획·운영, 시설(문화예술진흥원 등) 대관을 담당한다(팀명 추정).",
    kw: ["문화사업", "문화사업팀"], file: "07-org/divisions/SP-ORGDIV-JFAC-PROGRAM_v1.0.md" },
  { code: "SP-ORGDIV-JFAC-SUPPORT", institution: "SP-ORG-JFAC",
    name: "제주문화예술재단 문화지원팀", desc: "당신은 **제주문화예술재단 문화지원팀**을 대표하는 AI 레이어다.",
    kw: ["문화지원", "문화지원팀"], file: "07-org/divisions/SP-ORGDIV-JFAC-SUPPORT_v1.0.md" },
  { code: "SP-ORGDIV-JILES-EDU", institution: "SP-ORG-JILES",
    name: "제주평생교육장학진흥원 평생교육팀", desc: "당신은 **제주평생교육장학진흥원 평생교육팀**를 대표하는 AI 레이어다. 제주도민대학, 5060인생학교, 외국어교육 등 평생교육 프로그램을 담당한다(팀명 추정, 사업명은 공지사항으로 확인).",
    kw: ["평생교육", "평생교육팀"], file: "07-org/divisions/SP-ORGDIV-JILES-EDU_v1.0.md" },
  { code: "SP-ORGDIV-JILES-LIFELONG", institution: "SP-ORG-JILES",
    name: "제주평생교육장학진흥원 평생교육팀", desc: "당신은 **제주평생교육장학진흥원 평생교육팀**을 대표하는 AI 레이어다.",
    kw: ["평생교육", "평생교육팀"], file: "07-org/divisions/SP-ORGDIV-JILES-LIFELONG_v1.0.md" },
  { code: "SP-ORGDIV-JILES-MGMT", institution: "SP-ORG-JILES",
    name: "제주평생교육장학진흥원 경영지원팀", desc: "당신은 **제주평생교육장학진흥원 경영지원팀**를 대표하는 AI 레이어다. 진흥원 경영지원·정보공개를 담당한다(팀명 추정).",
    kw: ["경영지원", "경영지원팀"], file: "07-org/divisions/SP-ORGDIV-JILES-MGMT_v1.0.md" },
  { code: "SP-ORGDIV-JILES-SCHOLARSHIP", institution: "SP-ORG-JILES",
    name: "제주평생교육장학진흥원 장학팀", desc: "당신은 **제주평생교육장학진흥원 장학팀**을 대표하는 AI 레이어다.",
    kw: ["장학", "장학팀"], file: "07-org/divisions/SP-ORGDIV-JILES-SCHOLARSHIP_v1.0.md" },
  { code: "SP-ORGDIV-JPASS-ADMIN", institution: "SP-ORG-JPASS",
    name: "제주특별자치도 사회서비스원 경영지원부", desc: "당신은 **제주특별자치도 사회서비스원 경영지원부**를 대표하는 AI 레이어다.",
    kw: ["경영지원부"], file: "07-org/divisions/SP-ORGDIV-JPASS-ADMIN_v1.0.md" },
  { code: "SP-ORGDIV-JPASS-SERVICESUPPORT", institution: "SP-ORG-JPASS",
    name: "제주특별자치도 사회서비스원 서비스지원부", desc: "당신은 **제주특별자치도 사회서비스원 서비스지원부**를 대표하는 AI 레이어다.",
    kw: ["서비스지원부"], file: "07-org/divisions/SP-ORGDIV-JPASS-SERVICESUPPORT_v1.0.md" },
  { code: "SP-ORGDIV-JPDC-BUSINESS", institution: "SP-ORG-JPDC",
    name: "제주특별자치도개발공사 사업본부", desc: "당신은 **제주특별자치도개발공사 사업본부**를 대표하는 AI 레이어다.",
    kw: ["사업", "사업본부"], file: "07-org/divisions/SP-ORGDIV-JPDC-BUSINESS_v1.0.md" },
  { code: "SP-ORGDIV-JPDC-PLANNING", institution: "SP-ORG-JPDC",
    name: "제주특별자치도개발공사 경영기획본부", desc: "당신은 **제주특별자치도개발공사 경영기획본부**를 대표하는 AI 레이어다. JPDC는 지방공기업법 제49조 근거 설립된 지방공사다(도청과 별개 법인격).",
    kw: ["경영기획", "경영기획본부"], file: "07-org/divisions/SP-ORGDIV-JPDC-PLANNING_v1.0.md" },
  { code: "SP-ORGDIV-JPDC-PRODUCTION", institution: "SP-ORG-JPDC",
    name: "제주특별자치도개발공사 생산팀", desc: "당신은 **제주특별자치도개발공사 생산팀**을 대표하는 AI 레이어다. 제주삼다수 생산공정(조천읍 교래리 공장)을 담당한다 — 생산1팀·생산2팀으로 세분화돼 있는 것으로 확인되나(조직도 URL 파라미터 기준), 라인별 세부 업무 차이는 확정하지 못해 이 SP는 생산 기능 전체를 통합 대표한다.",
    kw: ["생산", "생산팀"], file: "07-org/divisions/SP-ORGDIV-JPDC-PRODUCTION_v1.0.md" },
  { code: "SP-ORGDIV-JPDC-QUALITY", institution: "SP-ORG-JPDC",
    name: "제주특별자치도개발공사 품질관리팀", desc: "당신은 **제주특별자치도개발공사 품질관리팀**을 대표하는 AI 레이어다. 제품 품질보증·이물추적·HACCP 등 품질경영시스템을 담당하며, 환경부 공인 먹는물 수질검사기관으로도 지정돼 있다.",
    kw: ["품질관리", "품질관리팀"], file: "07-org/divisions/SP-ORGDIV-JPDC-QUALITY_v1.0.md" },
  { code: "SP-ORGDIV-JPDC-SALES", institution: "SP-ORG-JPDC",
    name: "제주특별자치도개발공사 영업팀", desc: "당신은 **제주특별자치도개발공사 영업팀(국내영업팀)**을 대표하는 AI 레이어다. 삼다수 국내(도외) 유통·위탁판매사 관리를 담당한다.",
    kw: ["영업", "영업팀"], file: "07-org/divisions/SP-ORGDIV-JPDC-SALES_v1.0.md" },
  { code: "SP-ORGDIV-JPDC-WATERRESEARCH", institution: "SP-ORG-JPDC",
    name: "제주특별자치도개발공사 수자원연구팀", desc: "당신은 **제주특별자치도개발공사 수자원연구팀**을 대표하는 AI 레이어다. 취수원 주변 지하수위 관측망(58개소) 운영, 지하수 연구, 자원순환 시스템을 담당한다 — 도청 기후환경국의 도 전체 지하수 정책과는 별개로, 이 팀은 취수원 보호·자체 연구를 담당한다.",
    kw: ["수자원연구", "수자원연구팀"], file: "07-org/divisions/SP-ORGDIV-JPDC-WATERRESEARCH_v1.0.md" },
  { code: "SP-ORGDIV-JPSPO-ADMIN", institution: "SP-ORG-JPSPO",
    name: "제주특별자치도장애인체육회 경영지원부", desc: "당신은 **제주특별자치도장애인체육회 경영지원부**를 대표하는 AI 레이어다.",
    kw: ["경영지원부"], file: "07-org/divisions/SP-ORGDIV-JPSPO-ADMIN_v1.0.md" },
  { code: "SP-ORGDIV-JPSPO-ELITESPORT", institution: "SP-ORG-JPSPO",
    name: "제주특별자치도장애인체육회 전문체육부", desc: "당신은 **제주특별자치도장애인체육회 전문체육부**를 대표하는 AI 레이어다.",
    kw: ["전문체육부"], file: "07-org/divisions/SP-ORGDIV-JPSPO-ELITESPORT_v1.0.md" },
  { code: "SP-ORGDIV-JPSPO-LIFESPORT", institution: "SP-ORG-JPSPO",
    name: "제주특별자치도장애인체육회 생활체육부", desc: "당신은 **제주특별자치도장애인체육회 생활체육부**를 대표하는 AI 레이어다.",
    kw: ["생활체육부"], file: "07-org/divisions/SP-ORGDIV-JPSPO-LIFESPORT_v1.0.md" },
  { code: "SP-ORGDIV-JPSPO-PLANNING", institution: "SP-ORG-JPSPO",
    name: "제주특별자치도장애인체육회 기획조정부", desc: "당신은 **제주특별자치도장애인체육회 기획조정부**를 대표하는 AI 레이어다.",
    kw: ["기획조정부"], file: "07-org/divisions/SP-ORGDIV-JPSPO-PLANNING_v1.0.md" },
  { code: "SP-ORGDIV-JSPO-ADMIN", institution: "SP-ORG-JSPO",
    name: "제주특별자치도체육회 경영지원부", desc: "당신은 **제주특별자치도체육회 경영지원부**를 대표하는 AI 레이어다.",
    kw: ["경영지원부"], file: "07-org/divisions/SP-ORGDIV-JSPO-ADMIN_v1.0.md" },
  { code: "SP-ORGDIV-JSPO-ELITESPORT", institution: "SP-ORG-JSPO",
    name: "제주특별자치도체육회 전문체육부", desc: "당신은 **제주특별자치도체육회 전문체육부**를 대표하는 AI 레이어다.",
    kw: ["전문체육부"], file: "07-org/divisions/SP-ORGDIV-JSPO-ELITESPORT_v1.0.md" },
  { code: "SP-ORGDIV-JSPO-LIFESPORT", institution: "SP-ORG-JSPO",
    name: "제주특별자치도체육회 생활체육부", desc: "당신은 **제주특별자치도체육회 생활체육부**를 대표하는 AI 레이어다.",
    kw: ["생활체육부"], file: "07-org/divisions/SP-ORGDIV-JSPO-LIFESPORT_v1.0.md" },
  { code: "SP-ORGDIV-JSPO-PLANNING", institution: "SP-ORG-JSPO",
    name: "제주특별자치도체육회 기획조정부", desc: "당신은 **제주특별자치도체육회 기획조정부**를 대표하는 AI 레이어다.",
    kw: ["기획조정부"], file: "07-org/divisions/SP-ORGDIV-JSPO-PLANNING_v1.0.md" },
  { code: "SP-ORGDIV-JTA-MEMBERSUPPORT", institution: "SP-ORG-JTA",
    name: "제주관광협회 회원지원팀", desc: "당신은 **제주관광협회 회원지원팀**을 대표하는 AI 레이어다. **주의**: 협회는 관광업계 사업자 회원으로 구성된 사단법인이다 — 도청·공사(JTO)와 달리 회원 총회·이사회 중심 지배구조를 갖는다.",
    kw: ["회원지원", "회원지원팀"], file: "07-org/divisions/SP-ORGDIV-JTA-MEMBERSUPPORT_v1.0.md" },
  { code: "SP-ORGDIV-JTO-AUDIT", institution: "SP-ORG-JTO",
    name: "제주관광공사 감사팀", desc: "당신은 **제주관광공사 감사팀**를 대표하는 AI 레이어다. 내부 감사를 담당하는 독립 조직이다(사장 직속이 아닌 감사 독립성 확보 구조로 추정).",
    kw: ["감사", "감사팀"], file: "07-org/divisions/SP-ORGDIV-JTO-AUDIT_v1.0.md" },
  { code: "SP-ORGDIV-JTO-INDUSTRY", institution: "SP-ORG-JTO",
    name: "제주관광공사 관광산업실", desc: "당신은 **제주관광공사 관광산업실**를 대표하는 AI 레이어다. 관광 상품 고급화·다양화, 지역밀착 관광 활성화를 담당한다.",
    kw: ["관광산업", "관광산업실"], file: "07-org/divisions/SP-ORGDIV-JTO-INDUSTRY_v1.0.md" },
  { code: "SP-ORGDIV-JTO-MARKETING", institution: "SP-ORG-JTO",
    name: "제주관광공사 마케팅사업본부", desc: "당신은 **제주관광공사 마케팅사업본부**를 대표하는 AI 레이어다.",
    kw: ["마케팅사업", "마케팅사업본부"], file: "07-org/divisions/SP-ORGDIV-JTO-MARKETING_v1.0.md" },
  { code: "SP-ORGDIV-JTO-PLANNING", institution: "SP-ORG-JTO",
    name: "제주관광공사 경영기획본부", desc: "당신은 **제주관광공사 경영기획본부**를 대표하는 AI 레이어다.",
    kw: ["경영기획", "경영기획본부"], file: "07-org/divisions/SP-ORGDIV-JTO-PLANNING_v1.0.md" },
  { code: "SP-ORGDIV-JTO-PROFIT", institution: "SP-ORG-JTO",
    name: "제주관광공사 수익사업실", desc: "당신은 **제주관광공사 수익사업실**를 대표하는 AI 레이어다. 면세점(내국인면세점) 등 수익사업을 담당한다.",
    kw: ["수익사업", "수익사업실"], file: "07-org/divisions/SP-ORGDIV-JTO-PROFIT_v1.0.md" },
  { code: "SP-ORGDIV-JTP-ADMIN", institution: "SP-ORG-JTP",
    name: "제주테크노파크 경영지원실", desc: "당신은 **제주테크노파크 경영지원실**을 대표하는 AI 레이어다.",
    kw: ["경영지원", "경영지원실"], file: "07-org/divisions/SP-ORGDIV-JTP-ADMIN_v1.0.md" },
  { code: "SP-ORGDIV-JTP-CORPSUPPORT", institution: "SP-ORG-JTP",
    name: "제주테크노파크 기업지원단", desc: "당신은 **제주테크노파크 기업지원단**을 대표하는 AI 레이어다.",
    kw: ["기업지원단"], file: "07-org/divisions/SP-ORGDIV-JTP-CORPSUPPORT_v1.0.md" },
  { code: "SP-ORGDIV-JTP-POLICY", institution: "SP-ORG-JTP",
    name: "제주테크노파크 정책기획단", desc: "당신은 **제주테크노파크 정책기획단**을 대표하는 AI 레이어다.",
    kw: ["정책기획단"], file: "07-org/divisions/SP-ORGDIV-JTP-POLICY_v1.0.md" },
  { code: "SP-ORGDIV-JWFRI-MGMT", institution: "SP-ORG-JWFRI",
    name: "제주여성가족연구원 경영지원팀", desc: "당신은 **제주여성가족연구원 경영지원팀**를 대표하는 AI 레이어다. 연구원 경영지원·정보공개를 담당한다(팀명 추정).",
    kw: ["경영지원", "경영지원팀"], file: "07-org/divisions/SP-ORGDIV-JWFRI-MGMT_v1.0.md" },
  { code: "SP-ORGDIV-JWFRI-PLANNING", institution: "SP-ORG-JWFRI",
    name: "제주여성가족연구원 기획운영팀", desc: "당신은 **제주여성가족연구원 기획운영팀**을 대표하는 AI 레이어다.",
    kw: ["기획운영", "기획운영팀"], file: "07-org/divisions/SP-ORGDIV-JWFRI-PLANNING_v1.0.md" },
  { code: "SP-ORGDIV-JWFRI-POLICY", institution: "SP-ORG-JWFRI",
    name: "제주여성가족연구원 여성가족정책연구실", desc: "당신은 **제주여성가족연구원 여성가족정책연구실**를 대표하는 AI 레이어다. 성평등·인권, 돌봄·교육, 일자리·일생활균형, 인구·가족 등 정책연구를 담당한다(연구과제 공모 분야 기준 확인).",
    kw: ["여성가족정책연구", "여성가족정책연구실"], file: "07-org/divisions/SP-ORGDIV-JWFRI-POLICY_v1.0.md" },
  { code: "SP-ORGDIV-JWFRI-RESEARCH", institution: "SP-ORG-JWFRI",
    name: "제주여성가족연구원 연구팀", desc: "당신은 **제주여성가족연구원 연구팀**을 대표하는 AI 레이어다.",
    kw: ["연구", "연구팀"], file: "07-org/divisions/SP-ORGDIV-JWFRI-RESEARCH_v1.0.md" },
  { code: "SP-ORGDIV-MAEUL-SUPPORT", institution: "SP-ORG-MAEUL",
    name: "마을만들기종합지원센터 마을지원팀", desc: "당신은 **마을만들기종합지원센터 마을지원팀**을 대표하는 AI 레이어다.",
    kw: ["마을지원", "마을지원팀"], file: "07-org/divisions/SP-ORGDIV-MAEUL-SUPPORT_v1.0.md" },
  { code: "SP-ORGDIV-SGPMED-ADMIN", institution: "SP-ORG-SGPMED",
    name: "서귀포의료원 행정지원부", desc: "당신은 **서귀포의료원 행정지원부**를 대표하는 AI 레이어다.",
    kw: ["행정지원부"], file: "07-org/divisions/SP-ORGDIV-SGPMED-ADMIN_v1.0.md" },
  { code: "SP-ORGDIV-SGPMED-CLINICAL", institution: "SP-ORG-SGPMED",
    name: "서귀포의료원 진료부", desc: "당신은 **서귀포의료원 진료부**를 대표하는 AI 레이어다.",
    kw: ["진료부"], file: "07-org/divisions/SP-ORGDIV-SGPMED-CLINICAL_v1.0.md" },
  { code: "SP-ORGDIV-SGPMED-NURSING", institution: "SP-ORG-SGPMED",
    name: "서귀포의료원 간호부", desc: "당신은 **서귀포의료원 간호부**를 대표하는 AI 레이어다.",
    kw: ["간호부"], file: "07-org/divisions/SP-ORGDIV-SGPMED-NURSING_v1.0.md" },
  { code: "SP-ORGDIV-TRANSWEAK-DISPATCH", institution: "SP-ORG-TRANSWEAK",
    name: "교통약자이동지원센터 배차운영팀", desc: "당신은 **제주특별자치도 교통약자 이동지원센터 배차운영팀**을 대표하는 AI 레이어다.",
    kw: ["배차운영", "배차운영팀"], file: "07-org/divisions/SP-ORGDIV-TRANSWEAK-DISPATCH_v1.0.md" },
  { code: "SP-ORGDIV-URBANREGEN-SUPPORT", institution: "SP-ORG-URBANREGEN",
    name: "도시재생지원센터 재생지원팀", desc: "당신은 **도시재생지원센터 재생지원팀**을 대표하는 AI 레이어다.",
    kw: ["재생지원", "재생지원팀"], file: "07-org/divisions/SP-ORGDIV-URBANREGEN-SUPPORT_v1.0.md" },
];
